<?php

declare(strict_types=1);

namespace Database\Seeders\Backup;

use App\Infrastructure\Persistence\Eloquent\Models\Driver;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * DriversBackupSeeder
 *
 * This seeder restores the drivers table data from a backup.
 * Generated: 2026-02-07
 *
 * IMPORTANT: This seeder should ONLY run in local/development/staging environments.
 */
class DriversBackupSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Environment safety check - NEVER run in production
        if (app()->environment('production')) {
            $this->command->error('DriversBackupSeeder cannot run in production environment!');
            return;
        }

        $this->command->info('Seeding drivers backup data...');

        // Disable foreign key checks temporarily
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');

        $drivers = [
            [
                'id' => 1,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'Half-Byte',
                'slug' => 'half-byte',
                'email' => null,
                'phone' => null,
                'psn_id' => 'Half-Byte',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'Half-Byte',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 2,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'T F Eccles',
                'slug' => 'tfeccles',
                'email' => null,
                'phone' => null,
                'psn_id' => 'tfeccles',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'T F Eccles',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 3,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'Vert Wheeler',
                'slug' => 'vertwheeler07',
                'email' => null,
                'phone' => null,
                'psn_id' => 'Vertwheeler07',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'Vert Wheeler',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 4,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'AUSnicko9',
                'slug' => 'ausnicko9',
                'email' => null,
                'phone' => null,
                'psn_id' => 'AUSnicko9',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'AUSnicko9',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 5,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'Beats',
                'slug' => 'beats143',
                'email' => null,
                'phone' => null,
                'psn_id' => 'Beats143',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'Beats',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 6,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'Matt Dernedde',
                'slug' => 'ohdennn',
                'email' => null,
                'phone' => null,
                'psn_id' => 'ohdennn',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'Matt Dernedde',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 7,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'Alexb8891',
                'slug' => 'xtendedwarranty',
                'email' => null,
                'phone' => null,
                'psn_id' => 'Xtendedwarranty',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'Alexb8891',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 8,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'Kiwi_kart_racer9',
                'slug' => 'kiwi-kart-racer9',
                'email' => null,
                'phone' => null,
                'psn_id' => 'kiwi_kart_racer9',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'Kiwi_kart_racer9',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 9,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'E. Presley',
                'slug' => 'e-presley101',
                'email' => null,
                'phone' => null,
                'psn_id' => 'e_presley101',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'E. Presley',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 10,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'j. Farley',
                'slug' => 'j-farley',
                'email' => null,
                'phone' => null,
                'psn_id' => 'Selraf',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'Selraf',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 11,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'rae1982',
                'slug' => 'rae1982',
                'email' => null,
                'phone' => null,
                'psn_id' => 'Rae1982',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'rae1982',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 12,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'J.Nightingale',
                'slug' => 'jnightingale',
                'email' => null,
                'phone' => null,
                'psn_id' => 'LOW_NZ',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'LOW_NZ',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 13,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'Savage_Duck_75',
                'slug' => 'savage-duck-75',
                'email' => null,
                'phone' => null,
                'psn_id' => 'Savageduck_75',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'Savage Duck',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 14,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'Muzzie_013',
                'slug' => 'muzzie-013',
                'email' => null,
                'phone' => null,
                'psn_id' => 'Muzzie_013',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'Muzzie_013',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 15,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'K. Brown',
                'slug' => 'tacticalhomework',
                'email' => null,
                'phone' => null,
                'psn_id' => 'TacticalHomework',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'Kieran-B33',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 16,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'Rangeraus',
                'slug' => 'rangeraus',
                'email' => null,
                'phone' => null,
                'psn_id' => 'Rangeraus',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'Rangeraus',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 17,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'RBRHoges97',
                'slug' => 'rbrhoges97',
                'email' => null,
                'phone' => null,
                'psn_id' => 'RBRHoges97',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'RBRHoges97',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 18,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'Charlie chops',
                'slug' => 'mr-charlie-chops',
                'email' => null,
                'phone' => null,
                'psn_id' => 'mr_charlie_chops',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'Charlie chops',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 19,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'dani249',
                'slug' => 'walmar-anolso',
                'email' => null,
                'phone' => null,
                'psn_id' => 'Walmar_anolso',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'dani249',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 20,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'Easyprey007',
                'slug' => 'easyprey007',
                'email' => null,
                'phone' => null,
                'psn_id' => 'Easyprey007',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'Easyprey007',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 21,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'Wolfy 1961',
                'slug' => 'wolfy-1961',
                'email' => null,
                'phone' => null,
                'psn_id' => 'Wolfy_1961',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'Wolfy 1961',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 22,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'Bob Massie',
                'slug' => 'rpeem808',
                'email' => null,
                'phone' => null,
                'psn_id' => 'RPeeM808',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'Bob Massie',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 23,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'BritzLightning55',
                'slug' => 'britzlightning55',
                'email' => null,
                'phone' => null,
                'psn_id' => 'BritzLightning55',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'BritzLightning55',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 24,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'Sylveon with a gun',
                'slug' => 'gregzilla1971',
                'email' => null,
                'phone' => null,
                'psn_id' => 'Gregzilla1971',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'Sylveon with a gun',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 25,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'warrior2167',
                'slug' => 'warrior2167',
                'email' => null,
                'phone' => null,
                'psn_id' => 'warrior2167',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'warrior2167',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 26,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'JC_Blaize',
                'slug' => 'jc-blaize',
                'email' => null,
                'phone' => null,
                'psn_id' => 'Valymr_Blaize',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'Valymr_Blaize',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 27,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'UrsineSaturn9',
                'slug' => 'ursinesaturn9',
                'email' => null,
                'phone' => null,
                'psn_id' => 'UrsineSaturn9',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'UrsineSaturn9',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 28,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'Bluntman75',
                'slug' => 'blunty075',
                'email' => null,
                'phone' => null,
                'psn_id' => 'Blunty075',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'Bluntman75',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 29,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'pokeeetus',
                'slug' => 'pokeeetus',
                'email' => null,
                'phone' => null,
                'psn_id' => 'TanqR7286',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'pokeeetus',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 30,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'Snorxal',
                'slug' => 's2t-snorxal',
                'email' => null,
                'phone' => null,
                'psn_id' => 'S2T_Snorxal',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'Snorxal',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 31,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'X-3vi1 m00n',
                'slug' => 'x-3vi1-m00n',
                'email' => null,
                'phone' => null,
                'psn_id' => 'X-Evi1m00n',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'evilmoon',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 32,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'Stinky',
                'slug' => 'stinkytaylor',
                'email' => null,
                'phone' => null,
                'psn_id' => 'StinkyTaylor',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'Stinky',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 33,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'tolley_',
                'slug' => 'tolley',
                'email' => null,
                'phone' => null,
                'psn_id' => 'tolley__',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'troll555',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 34,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'Donsflyup',
                'slug' => 'wait6moreseconds',
                'email' => null,
                'phone' => null,
                'psn_id' => 'wait6moreseconds',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'Donsflyup',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 35,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'Whizz94',
                'slug' => 'whizz94',
                'email' => null,
                'phone' => null,
                'psn_id' => 'Whizz94',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'Whizz94',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 36,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'Schumojo 13',
                'slug' => 'schumojo-13',
                'email' => null,
                'phone' => null,
                'psn_id' => 'Schumojo13',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'Schumojo13',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 37,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'slarty',
                'slug' => 'slartybar',
                'email' => null,
                'phone' => null,
                'psn_id' => 'slartybar',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'slarty',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 38,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'fezza21',
                'slug' => 'fezza-21',
                'email' => null,
                'phone' => null,
                'psn_id' => 'FeZZa_21',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'fezza21',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 39,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'anders_race',
                'slug' => 'anders-race',
                'email' => null,
                'phone' => null,
                'psn_id' => 'anders_race',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'anders_race',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 40,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'Steve_73_GOOF',
                'slug' => 'steve-73-goof',
                'email' => null,
                'phone' => null,
                'psn_id' => 'Steve_73_GOOF',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'Steve_73_GOOF',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 41,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'Dstinct_Andrew',
                'slug' => 'dstinct-andrew',
                'email' => null,
                'phone' => null,
                'psn_id' => 'Dstinct_Andrew',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'Dstinct_Andrew',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 42,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'lpalmonds',
                'slug' => 'lpalmonds',
                'email' => null,
                'phone' => null,
                'psn_id' => 'lpalmonds',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'lpalmonds',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 43,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'T-GT Racing',
                'slug' => 't-gt-racing',
                'email' => null,
                'phone' => null,
                'psn_id' => 'T-GT_Racing',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'T-GT Racing',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 44,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'Doodah27',
                'slug' => 'doodah27',
                'email' => null,
                'phone' => null,
                'psn_id' => 'Doodah27',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'Doodah27',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 45,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'Dash_Vanguard',
                'slug' => 'dash-vanguard',
                'email' => null,
                'phone' => null,
                'psn_id' => 'Dash_Vanguard',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'Dash_Vanguard',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 46,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'seowster',
                'slug' => 'seowsteraus',
                'email' => null,
                'phone' => null,
                'psn_id' => 'seowsterAUS',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'seowster',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 47,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'Emmo',
                'slug' => 'emmo46',
                'email' => null,
                'phone' => null,
                'psn_id' => 'emmo46',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'Emmo',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 48,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'Natalie WA',
                'slug' => 'natalie-275',
                'email' => null,
                'phone' => null,
                'psn_id' => 'Natalie_275',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'Natalie WA',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 49,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'Luppo',
                'slug' => 'social-shocker5',
                'email' => null,
                'phone' => null,
                'psn_id' => 'social-shocker5',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'Luppo',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 50,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'Ozglenn',
                'slug' => 'ozglenn0513',
                'email' => null,
                'phone' => null,
                'psn_id' => 'ozglenn0513',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'Ozglenn',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 51,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'btwong',
                'slug' => 'btwong',
                'email' => null,
                'phone' => null,
                'psn_id' => 'btwong10',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'btwong10',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 52,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'isaacfog01',
                'slug' => 'fogdog01',
                'email' => null,
                'phone' => null,
                'psn_id' => 'fogdog01',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'isaacfog01',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 53,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'ITZ_JZH17',
                'slug' => 'itz-josh15',
                'email' => null,
                'phone' => null,
                'psn_id' => 'ITZ_JOSH15',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'ITZ_JZH17',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 54,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'Viperzed',
                'slug' => 'viperzed',
                'email' => null,
                'phone' => null,
                'psn_id' => 'Viperzed',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => null,
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 55,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'JimothyPayload',
                'slug' => 'jimothypayload',
                'email' => null,
                'phone' => null,
                'psn_id' => 'JimothyPayload',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'Jimothy Payload',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 56,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'CaptainRisky21',
                'slug' => 'captainrisky21',
                'email' => null,
                'phone' => null,
                'psn_id' => 'CaptainRisky21',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => null,
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 57,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'MINT_Matt',
                'slug' => 'mint-matt',
                'email' => null,
                'phone' => null,
                'psn_id' => 'MINT_Matt',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'Matt Simmons',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 58,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'BlockyRex1',
                'slug' => 'blockyrex1',
                'email' => null,
                'phone' => null,
                'psn_id' => 'BlockyRex1',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => null,
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 59,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'sidawg2',
                'slug' => 'sidawg2',
                'email' => null,
                'phone' => null,
                'psn_id' => 'sidawg2',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => null,
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 60,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'Matthyus',
                'slug' => 'johnnoclint',
                'email' => null,
                'phone' => null,
                'psn_id' => 'johnnoclint',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'Matthyus',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 61,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'Selduin',
                'slug' => 'selduin',
                'email' => null,
                'phone' => null,
                'psn_id' => 'Selduin',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'Selduin',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 62,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'B. CakePie',
                'slug' => 'b-cakepie',
                'email' => null,
                'phone' => null,
                'psn_id' => 'B. CakePie',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => null,
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 63,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'DRZ-Hatfield',
                'slug' => 'drz-hatfield',
                'email' => null,
                'phone' => null,
                'psn_id' => 'DRZ-Hatfield',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'DRZ-Hatfield',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 64,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'Jelly Mechanic',
                'slug' => 'jelly-mechanic',
                'email' => null,
                'phone' => null,
                'psn_id' => 'arbee5555',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => null,
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 65,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'TimAnt_46',
                'slug' => 'timant-46',
                'email' => null,
                'phone' => null,
                'psn_id' => 'TimAnt_46',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'TimAnt46',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 66,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'arnoldwa',
                'slug' => 'arnoldwa',
                'email' => null,
                'phone' => null,
                'psn_id' => 'arnoldwa',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'arnold',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 67,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'AverageDad',
                'slug' => 'averagedad',
                'email' => null,
                'phone' => null,
                'psn_id' => 'LuckyDenverM1nt',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'AverageDAD',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 68,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'Hatchy3_',
                'slug' => 'hatchy3',
                'email' => null,
                'phone' => null,
                'psn_id' => 'Hatchy3_',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'Hatchy3_',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 69,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'bananajosh1',
                'slug' => 'bananajosh1',
                'email' => null,
                'phone' => null,
                'psn_id' => 'GT_bananajosh1',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'bananajosh1',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 70,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'Zac',
                'slug' => 'zac-l98',
                'email' => null,
                'phone' => null,
                'psn_id' => 'DrGastroBoy',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'Zac_l98',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 71,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'JJP',
                'slug' => 'jjp',
                'email' => null,
                'phone' => null,
                'psn_id' => 'LordFarquaad521',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'JJP',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 72,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'BKXI',
                'slug' => 'bkxi',
                'email' => null,
                'phone' => null,
                'psn_id' => 'BKXI',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'BKXI',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 73,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'sentry',
                'slug' => 'sentry',
                'email' => null,
                'phone' => null,
                'psn_id' => 'sentryAU',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'sentry',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 74,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'Kaladin',
                'slug' => 'kaladin501',
                'email' => null,
                'phone' => null,
                'psn_id' => 'kaladin501',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'kaladin',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 75,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'Danimal',
                'slug' => 'danimal-242',
                'email' => null,
                'phone' => null,
                'psn_id' => 'danimal_242',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'danimal_242',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 76,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'B. Purton',
                'slug' => 'b-purton',
                'email' => null,
                'phone' => null,
                'psn_id' => 'Purts91',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'B.Purton',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 77,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'Nik_Makozi',
                'slug' => 'nik-makozi',
                'email' => null,
                'phone' => null,
                'psn_id' => 'Nik_Makozi',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'k.oh.dee',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-02-04 03:10:10',
                'deleted_at' => null,
            ],
            [
                'id' => 78,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'redleeTTV',
                'slug' => 'redleettv',
                'email' => null,
                'phone' => null,
                'psn_id' => 'redleeTTV',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'redleeTTV',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 79,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'RidwanF1',
                'slug' => 'ridwanf1',
                'email' => null,
                'phone' => null,
                'psn_id' => 'RidwanF1',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'ridwanf1',
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
                'deleted_at' => null,
            ],
            [
                'id' => 80,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'DJMaster55',
                'slug' => 'djmaster55',
                'email' => null,
                'phone' => null,
                'psn_id' => 'TheDJMaster55',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => null,
                'created_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-02-04 03:08:35',
                'deleted_at' => null,
            ],
            [
                'id' => 84,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'BobertNn',
                'slug' => 'bobertnn',
                'email' => null,
                'phone' => null,
                'psn_id' => 'bobert',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => null,
                'created_at' => '2026-01-22 10:04:41',
                'updated_at' => '2026-01-25 05:03:16',
                'deleted_at' => null,
            ],
            [
                'id' => 85,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'KanusNn',
                'slug' => 'kanusnn',
                'email' => null,
                'phone' => null,
                'psn_id' => 'Kanus',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => null,
                'created_at' => '2026-01-22 10:08:10',
                'updated_at' => '2026-01-22 10:09:53',
                'deleted_at' => null,
            ],
            [
                'id' => 86,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'RubesNn',
                'slug' => 'rubesnn',
                'email' => null,
                'phone' => null,
                'psn_id' => 'Rubes',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => null,
                'created_at' => '2026-01-22 10:09:40',
                'updated_at' => '2026-01-22 10:09:40',
                'deleted_at' => null,
            ],
            [
                'id' => 87,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'MilsyNN',
                'slug' => 'milsynn',
                'email' => null,
                'phone' => null,
                'psn_id' => 'milsy',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => null,
                'created_at' => '2026-01-22 10:10:47',
                'updated_at' => '2026-01-22 10:10:47',
                'deleted_at' => null,
            ],
            [
                'id' => 88,
                'first_name' => 'btwong_fn',
                'last_name' => 'btwong_ln',
                'nickname' => 'btwong_nickname',
                'slug' => 'g-man',
                'email' => null,
                'phone' => null,
                'psn_id' => 'btwong_psn_id',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => null,
                'created_at' => '2026-01-22 10:11:06',
                'updated_at' => '2026-01-22 10:11:19',
                'deleted_at' => null,
            ],
            [
                'id' => 89,
                'first_name' => null,
                'last_name' => null,
                'nickname' => null,
                'slug' => 'driver-psn-roger',
                'email' => null,
                'phone' => null,
                'psn_id' => 'Roger',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => null,
                'created_at' => '2026-01-22 10:12:52',
                'updated_at' => '2026-01-22 10:12:52',
                'deleted_at' => null,
            ],
            [
                'id' => 90,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'Matt',
                'slug' => 'matt',
                'email' => null,
                'phone' => null,
                'psn_id' => 'MAtty',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'Matt',
                'created_at' => '2026-01-22 10:18:36',
                'updated_at' => '2026-01-22 10:18:36',
                'deleted_at' => null,
            ],
            [
                'id' => 91,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'dicordssss',
                'slug' => 'dicordssss',
                'email' => null,
                'phone' => null,
                'psn_id' => 'dicord',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'dicord',
                'created_at' => '2026-01-22 10:19:11',
                'updated_at' => '2026-01-22 10:19:57',
                'deleted_at' => null,
            ],
            [
                'id' => 92,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'Randm90',
                'slug' => 'randm90',
                'email' => null,
                'phone' => null,
                'psn_id' => 'Randm90',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => null,
                'created_at' => '2026-01-30 04:27:10',
                'updated_at' => '2026-01-30 04:27:10',
                'deleted_at' => null,
            ],
            [
                'id' => 93,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'ReignOfFire87',
                'slug' => 'reignoffire87',
                'email' => null,
                'phone' => null,
                'psn_id' => 'ReignOfFire87',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => null,
                'created_at' => '2026-01-30 04:28:35',
                'updated_at' => '2026-01-30 04:28:35',
                'deleted_at' => null,
            ],
            [
                'id' => 94,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'Waterarrow',
                'slug' => 'waterarrow',
                'email' => null,
                'phone' => null,
                'psn_id' => 'CP_Waterarrow',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => null,
                'created_at' => '2026-01-30 04:29:30',
                'updated_at' => '2026-01-30 04:29:30',
                'deleted_at' => null,
            ],
            [
                'id' => 95,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'Lagoon_j',
                'slug' => 'lagoon-j',
                'email' => null,
                'phone' => null,
                'psn_id' => 'Lagoon_j',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'Lagoon_j',
                'created_at' => '2026-01-30 04:29:44',
                'updated_at' => '2026-01-30 04:36:49',
                'deleted_at' => null,
            ],
            [
                'id' => 96,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'Tube-nvnz  🇳🇿 🇿🇦',
                'slug' => 'tube-nvnz',
                'email' => null,
                'phone' => null,
                'psn_id' => 'Nvnz-tube',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'Tube-nvnz',
                'created_at' => '2026-01-30 04:30:03',
                'updated_at' => '2026-01-30 04:36:36',
                'deleted_at' => null,
            ],
            [
                'id' => 97,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'AMS_Andrew',
                'slug' => 'ams-andrew',
                'email' => null,
                'phone' => null,
                'psn_id' => 'AMS_Andrew',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => null,
                'created_at' => '2026-01-30 04:33:40',
                'updated_at' => '2026-01-30 04:33:40',
                'deleted_at' => null,
            ],
            [
                'id' => 98,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'BIL',
                'slug' => 'bil',
                'email' => null,
                'phone' => null,
                'psn_id' => 'King_Kabe17',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => null,
                'created_at' => '2026-01-30 04:33:53',
                'updated_at' => '2026-01-30 04:33:53',
                'deleted_at' => null,
            ],
            [
                'id' => 99,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'Heefy82',
                'slug' => 'heefy82',
                'email' => null,
                'phone' => null,
                'psn_id' => 'Heefy82',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => null,
                'created_at' => '2026-01-30 04:34:09',
                'updated_at' => '2026-01-30 04:34:09',
                'deleted_at' => null,
            ],
            [
                'id' => 100,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'nuff6969',
                'slug' => 'nuff6969',
                'email' => null,
                'phone' => null,
                'psn_id' => 'The_____Lost2',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'nuff6969',
                'created_at' => '2026-01-30 04:35:49',
                'updated_at' => '2026-01-30 04:36:15',
                'deleted_at' => null,
            ],
            [
                'id' => 101,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'Anon666',
                'slug' => 'anon666',
                'email' => null,
                'phone' => null,
                'psn_id' => 'Anon666HURT',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => null,
                'created_at' => '2026-01-30 04:37:19',
                'updated_at' => '2026-01-30 04:37:19',
                'deleted_at' => null,
            ],
            [
                'id' => 102,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'ragguoc',
                'slug' => 'ragguoc',
                'email' => null,
                'phone' => null,
                'psn_id' => 'ragguoc',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => null,
                'created_at' => '2026-01-30 04:37:55',
                'updated_at' => '2026-01-30 04:37:55',
                'deleted_at' => null,
            ],
            [
                'id' => 103,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'Easty',
                'slug' => 'easty',
                'email' => null,
                'phone' => null,
                'psn_id' => 'jkeast',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => null,
                'created_at' => '2026-01-30 04:38:11',
                'updated_at' => '2026-01-30 04:38:11',
                'deleted_at' => null,
            ],
            [
                'id' => 104,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'Scozzii',
                'slug' => 'scozzii',
                'email' => null,
                'phone' => null,
                'psn_id' => 'SC0BBI1',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'Scozzii',
                'created_at' => '2026-01-30 04:38:26',
                'updated_at' => '2026-01-30 04:39:14',
                'deleted_at' => null,
            ],
            [
                'id' => 105,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'Greeny',
                'slug' => 'greeny',
                'email' => null,
                'phone' => null,
                'psn_id' => 'Greenysimracing',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'Greeny',
                'created_at' => '2026-01-30 04:38:37',
                'updated_at' => '2026-01-30 04:39:08',
                'deleted_at' => null,
            ],
            [
                'id' => 106,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'Pubs16',
                'slug' => 'pubs16',
                'email' => null,
                'phone' => null,
                'psn_id' => 'SR_Pubs16',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'Pubs16',
                'created_at' => '2026-01-30 04:38:53',
                'updated_at' => '2026-01-30 04:38:53',
                'deleted_at' => null,
            ],
            [
                'id' => 107,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'rockynz',
                'slug' => 'rockynz',
                'email' => null,
                'phone' => null,
                'psn_id' => 'rockynz',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'rockynz',
                'created_at' => '2026-01-30 04:39:25',
                'updated_at' => '2026-01-30 04:39:25',
                'deleted_at' => null,
            ],
            [
                'id' => 108,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'blambo',
                'slug' => 'blambo',
                'email' => null,
                'phone' => null,
                'psn_id' => 'blambozor',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'blambo',
                'created_at' => '2026-01-30 04:39:51',
                'updated_at' => '2026-01-30 04:39:51',
                'deleted_at' => null,
            ],
            [
                'id' => 109,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'LordFaquaad521',
                'slug' => 'lordfaquaad521',
                'email' => null,
                'phone' => null,
                'psn_id' => 'LordFaquaad521',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'LordFaquaad521',
                'created_at' => '2026-01-30 04:41:59',
                'updated_at' => '2026-01-30 04:41:59',
                'deleted_at' => null,
            ],
            [
                'id' => 110,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'Redlee',
                'slug' => 'redlee',
                'email' => null,
                'phone' => null,
                'psn_id' => 'RedLee',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => 'Redlee',
                'created_at' => '2026-01-30 04:41:59',
                'updated_at' => '2026-01-30 04:41:59',
                'deleted_at' => null,
            ],
            [
                'id' => 111,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'KangarooPhuka',
                'slug' => 'kangaroophuka',
                'email' => null,
                'phone' => null,
                'psn_id' => 'KangarooPhuka',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => null,
                'created_at' => '2026-02-04 03:00:24',
                'updated_at' => '2026-02-04 03:00:24',
                'deleted_at' => null,
            ],
            [
                'id' => 112,
                'first_name' => null,
                'last_name' => null,
                'nickname' => 'HBMotorNZ',
                'slug' => 'hbmotornz',
                'email' => null,
                'phone' => null,
                'psn_id' => 'HBMotorNZ',
                'iracing_id' => null,
                'iracing_customer_id' => null,
                'discord_id' => null,
                'created_at' => '2026-02-04 03:02:04',
                'updated_at' => '2026-02-04 03:02:04',
                'deleted_at' => null,
            ],
        ];

        foreach ($drivers as $driversData) {
            Driver::updateOrCreate(
                ['id' => $driversData['id']],
                $driversData
            );
        }

        // Re-enable foreign key checks
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $this->command->info('DriversBackupSeeder seeded successfully. Total records: ' . count($drivers));
    }
}
