<?php

declare(strict_types=1);

namespace Database\Seeders\Backup;

use App\Infrastructure\Persistence\Eloquent\Models\LeagueDriverEloquent;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * LeagueDriversBackupSeeder
 *
 * This seeder restores the league_drivers table data from a backup.
 * Generated: 2026-02-06
 *
 * IMPORTANT: This seeder should ONLY run in local/development/staging environments.
 * Dependencies: LeaguesBackupSeeder, DriversBackupSeeder must run first
 */
class LeagueDriversBackupSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Environment safety check - NEVER run in production
        if (app()->environment('production')) {
            $this->command->error('LeagueDriversBackupSeeder cannot run in production environment!');
            return;
        }

        $this->command->info('Seeding league_drivers backup data...');

        // Disable foreign key checks temporarily
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');

        $league_drivers = [
            [
                'id' => 1,
                'league_id' => 1,
                'driver_id' => 1,
                'driver_number' => 21,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 2,
                'league_id' => 1,
                'driver_id' => 2,
                'driver_number' => 52,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 3,
                'league_id' => 1,
                'driver_id' => 3,
                'driver_number' => 7,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 4,
                'league_id' => 1,
                'driver_id' => 4,
                'driver_number' => 91,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 5,
                'league_id' => 1,
                'driver_id' => 5,
                'driver_number' => 62,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 6,
                'league_id' => 1,
                'driver_id' => 6,
                'driver_number' => 50,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 7,
                'league_id' => 1,
                'driver_id' => 7,
                'driver_number' => 11,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 8,
                'league_id' => 1,
                'driver_id' => 8,
                'driver_number' => 98,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 9,
                'league_id' => 1,
                'driver_id' => 9,
                'driver_number' => 63,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 10,
                'league_id' => 1,
                'driver_id' => 10,
                'driver_number' => 65,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 11,
                'league_id' => 1,
                'driver_id' => 11,
                'driver_number' => 290,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 12,
                'league_id' => 1,
                'driver_id' => 12,
                'driver_number' => 22,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 13,
                'league_id' => 1,
                'driver_id' => 13,
                'driver_number' => 67,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 14,
                'league_id' => 1,
                'driver_id' => 14,
                'driver_number' => 13,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 15,
                'league_id' => 1,
                'driver_id' => 15,
                'driver_number' => 76,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 16,
                'league_id' => 1,
                'driver_id' => 16,
                'driver_number' => 82,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 17,
                'league_id' => 1,
                'driver_id' => 17,
                'driver_number' => 97,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 18,
                'league_id' => 1,
                'driver_id' => 18,
                'driver_number' => 34,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 19,
                'league_id' => 1,
                'driver_id' => 19,
                'driver_number' => 12,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 20,
                'league_id' => 1,
                'driver_id' => 20,
                'driver_number' => 63,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 21,
                'league_id' => 1,
                'driver_id' => 21,
                'driver_number' => 16,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 22,
                'league_id' => 1,
                'driver_id' => 22,
                'driver_number' => 809,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 23,
                'league_id' => 1,
                'driver_id' => 23,
                'driver_number' => 55,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 24,
                'league_id' => 1,
                'driver_id' => 24,
                'driver_number' => 135,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 25,
                'league_id' => 1,
                'driver_id' => 25,
                'driver_number' => 25,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 26,
                'league_id' => 1,
                'driver_id' => 26,
                'driver_number' => 212,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 27,
                'league_id' => 1,
                'driver_id' => 27,
                'driver_number' => 42,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 28,
                'league_id' => 1,
                'driver_id' => 28,
                'driver_number' => 75,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 29,
                'league_id' => 1,
                'driver_id' => 29,
                'driver_number' => 44,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 30,
                'league_id' => 1,
                'driver_id' => 30,
                'driver_number' => 39,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 31,
                'league_id' => 1,
                'driver_id' => 31,
                'driver_number' => 88,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 32,
                'league_id' => 1,
                'driver_id' => 32,
                'driver_number' => 66,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 33,
                'league_id' => 1,
                'driver_id' => 33,
                'driver_number' => 28,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 34,
                'league_id' => 1,
                'driver_id' => 34,
                'driver_number' => 93,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 35,
                'league_id' => 1,
                'driver_id' => 35,
                'driver_number' => 26,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 36,
                'league_id' => 1,
                'driver_id' => 36,
                'driver_number' => 77,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 37,
                'league_id' => 1,
                'driver_id' => 37,
                'driver_number' => 101,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 38,
                'league_id' => 1,
                'driver_id' => 38,
                'driver_number' => 21,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 39,
                'league_id' => 1,
                'driver_id' => 39,
                'driver_number' => 90,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 40,
                'league_id' => 1,
                'driver_id' => 40,
                'driver_number' => 73,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 41,
                'league_id' => 1,
                'driver_id' => 41,
                'driver_number' => 1,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 42,
                'league_id' => 1,
                'driver_id' => 42,
                'driver_number' => null,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 43,
                'league_id' => 1,
                'driver_id' => 43,
                'driver_number' => 44,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 44,
                'league_id' => 1,
                'driver_id' => 44,
                'driver_number' => null,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 45,
                'league_id' => 1,
                'driver_id' => 45,
                'driver_number' => 383,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 46,
                'league_id' => 1,
                'driver_id' => 46,
                'driver_number' => 27,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 47,
                'league_id' => 1,
                'driver_id' => 47,
                'driver_number' => 5,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 48,
                'league_id' => 1,
                'driver_id' => 48,
                'driver_number' => 275,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 49,
                'league_id' => 1,
                'driver_id' => 49,
                'driver_number' => 14,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 50,
                'league_id' => 1,
                'driver_id' => 50,
                'driver_number' => 13,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 51,
                'league_id' => 1,
                'driver_id' => 51,
                'driver_number' => 10,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 52,
                'league_id' => 1,
                'driver_id' => 52,
                'driver_number' => 99,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 53,
                'league_id' => 1,
                'driver_id' => 53,
                'driver_number' => 77,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 54,
                'league_id' => 1,
                'driver_id' => 54,
                'driver_number' => null,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 55,
                'league_id' => 1,
                'driver_id' => 55,
                'driver_number' => 123,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 56,
                'league_id' => 1,
                'driver_id' => 56,
                'driver_number' => null,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 57,
                'league_id' => 1,
                'driver_id' => 57,
                'driver_number' => 8,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 58,
                'league_id' => 1,
                'driver_id' => 58,
                'driver_number' => null,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 59,
                'league_id' => 1,
                'driver_id' => 59,
                'driver_number' => null,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 60,
                'league_id' => 1,
                'driver_id' => 60,
                'driver_number' => 95,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 61,
                'league_id' => 1,
                'driver_id' => 61,
                'driver_number' => 81,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 62,
                'league_id' => 1,
                'driver_id' => 62,
                'driver_number' => null,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 63,
                'league_id' => 1,
                'driver_id' => 63,
                'driver_number' => 3,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 64,
                'league_id' => 1,
                'driver_id' => 64,
                'driver_number' => null,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 65,
                'league_id' => 1,
                'driver_id' => 65,
                'driver_number' => 22,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 66,
                'league_id' => 1,
                'driver_id' => 66,
                'driver_number' => null,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 67,
                'league_id' => 1,
                'driver_id' => 67,
                'driver_number' => 33,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 68,
                'league_id' => 1,
                'driver_id' => 68,
                'driver_number' => 3,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 69,
                'league_id' => 1,
                'driver_id' => 69,
                'driver_number' => 28,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 70,
                'league_id' => 1,
                'driver_id' => 70,
                'driver_number' => 20,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 71,
                'league_id' => 1,
                'driver_id' => 71,
                'driver_number' => 52,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 72,
                'league_id' => 1,
                'driver_id' => 72,
                'driver_number' => 11,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 73,
                'league_id' => 1,
                'driver_id' => 73,
                'driver_number' => 2,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 74,
                'league_id' => 1,
                'driver_id' => 74,
                'driver_number' => 164,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 75,
                'league_id' => 1,
                'driver_id' => 75,
                'driver_number' => 24,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 76,
                'league_id' => 1,
                'driver_id' => 76,
                'driver_number' => 91,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 77,
                'league_id' => 1,
                'driver_id' => 77,
                'driver_number' => 7,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:50',
            ],
            [
                'id' => 78,
                'league_id' => 1,
                'driver_id' => 78,
                'driver_number' => 23,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:50',
                'updated_at' => '2026-02-06 05:08:51',
            ],
            [
                'id' => 79,
                'league_id' => 1,
                'driver_id' => 79,
                'driver_number' => 14,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:51',
                'updated_at' => '2026-02-06 05:08:51',
            ],
            [
                'id' => 80,
                'league_id' => 1,
                'driver_id' => 80,
                'driver_number' => 55,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-06 05:08:51',
                'updated_at' => '2026-02-06 05:08:51',
            ],
        ];

        foreach ($league_drivers as $leagueDriversData) {
            LeagueDriverEloquent::updateOrCreate(
                ['id' => $leagueDriversData['id']],
                $leagueDriversData
            );
        }

        // Re-enable foreign key checks
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $this->command->info('LeagueDriversBackupSeeder seeded successfully. Total records: ' . count($league_drivers));
    }
}
