<?php

declare(strict_types=1);

namespace Database\Seeders\Backup;

use App\Infrastructure\Persistence\Eloquent\Models\LeagueDriverEloquent;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * LeagueDriversBackupSeeder
 *
 * This seeder restores the league_drivers table data from a backup.
 * Generated: 2026-02-07
 *
 * IMPORTANT: This seeder should ONLY run in local/development/staging environments.
 * Dependencies: LeaguesBackupSeeder, DriversBackupSeeder must run first
 */
class LeagueDriversBackupSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Environment safety check - NEVER run in production
        if (app()->environment('production')) {
            $this->command->error('LeagueDriversBackupSeeder cannot run in production environment!');
            return;
        }

        $this->command->info('Seeding league_drivers backup data...');

        // Disable foreign key checks temporarily
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');

        $league_drivers = [
            [
                'id' => 1,
                'league_id' => 1,
                'driver_id' => 1,
                'driver_number' => 21,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 2,
                'league_id' => 1,
                'driver_id' => 2,
                'driver_number' => 52,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 3,
                'league_id' => 1,
                'driver_id' => 3,
                'driver_number' => 7,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 4,
                'league_id' => 1,
                'driver_id' => 4,
                'driver_number' => 91,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 5,
                'league_id' => 1,
                'driver_id' => 5,
                'driver_number' => 62,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 6,
                'league_id' => 1,
                'driver_id' => 6,
                'driver_number' => 50,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 7,
                'league_id' => 1,
                'driver_id' => 7,
                'driver_number' => 11,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 8,
                'league_id' => 1,
                'driver_id' => 8,
                'driver_number' => 98,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 9,
                'league_id' => 1,
                'driver_id' => 9,
                'driver_number' => 63,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 10,
                'league_id' => 1,
                'driver_id' => 10,
                'driver_number' => 65,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 11,
                'league_id' => 1,
                'driver_id' => 11,
                'driver_number' => 290,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 12,
                'league_id' => 1,
                'driver_id' => 12,
                'driver_number' => 22,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 13,
                'league_id' => 1,
                'driver_id' => 13,
                'driver_number' => 67,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 14,
                'league_id' => 1,
                'driver_id' => 14,
                'driver_number' => 13,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 15,
                'league_id' => 1,
                'driver_id' => 15,
                'driver_number' => 76,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 16,
                'league_id' => 1,
                'driver_id' => 16,
                'driver_number' => 82,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 17,
                'league_id' => 1,
                'driver_id' => 17,
                'driver_number' => 97,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 18,
                'league_id' => 1,
                'driver_id' => 18,
                'driver_number' => 34,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 19,
                'league_id' => 1,
                'driver_id' => 19,
                'driver_number' => 12,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 20,
                'league_id' => 1,
                'driver_id' => 20,
                'driver_number' => 63,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 21,
                'league_id' => 1,
                'driver_id' => 21,
                'driver_number' => 16,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 22,
                'league_id' => 1,
                'driver_id' => 22,
                'driver_number' => 809,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 23,
                'league_id' => 1,
                'driver_id' => 23,
                'driver_number' => 55,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 24,
                'league_id' => 1,
                'driver_id' => 24,
                'driver_number' => 135,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 25,
                'league_id' => 1,
                'driver_id' => 25,
                'driver_number' => 25,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 26,
                'league_id' => 1,
                'driver_id' => 26,
                'driver_number' => 212,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 27,
                'league_id' => 1,
                'driver_id' => 27,
                'driver_number' => 42,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 28,
                'league_id' => 1,
                'driver_id' => 28,
                'driver_number' => 75,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 29,
                'league_id' => 1,
                'driver_id' => 29,
                'driver_number' => 44,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 30,
                'league_id' => 1,
                'driver_id' => 30,
                'driver_number' => 39,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 31,
                'league_id' => 1,
                'driver_id' => 31,
                'driver_number' => 88,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 32,
                'league_id' => 1,
                'driver_id' => 32,
                'driver_number' => 66,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 33,
                'league_id' => 1,
                'driver_id' => 33,
                'driver_number' => 28,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 34,
                'league_id' => 1,
                'driver_id' => 34,
                'driver_number' => 93,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 35,
                'league_id' => 1,
                'driver_id' => 35,
                'driver_number' => 26,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 36,
                'league_id' => 1,
                'driver_id' => 36,
                'driver_number' => 77,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 37,
                'league_id' => 1,
                'driver_id' => 37,
                'driver_number' => 101,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 38,
                'league_id' => 1,
                'driver_id' => 38,
                'driver_number' => 21,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 39,
                'league_id' => 1,
                'driver_id' => 39,
                'driver_number' => 90,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 40,
                'league_id' => 1,
                'driver_id' => 40,
                'driver_number' => 73,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 41,
                'league_id' => 1,
                'driver_id' => 41,
                'driver_number' => 1,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 42,
                'league_id' => 1,
                'driver_id' => 42,
                'driver_number' => null,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 43,
                'league_id' => 1,
                'driver_id' => 43,
                'driver_number' => 44,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 44,
                'league_id' => 1,
                'driver_id' => 44,
                'driver_number' => null,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 45,
                'league_id' => 1,
                'driver_id' => 45,
                'driver_number' => 383,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 46,
                'league_id' => 1,
                'driver_id' => 46,
                'driver_number' => 27,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 47,
                'league_id' => 1,
                'driver_id' => 47,
                'driver_number' => 5,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 48,
                'league_id' => 1,
                'driver_id' => 48,
                'driver_number' => 275,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 49,
                'league_id' => 1,
                'driver_id' => 49,
                'driver_number' => 14,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 50,
                'league_id' => 1,
                'driver_id' => 50,
                'driver_number' => 13,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 51,
                'league_id' => 1,
                'driver_id' => 51,
                'driver_number' => 10,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 52,
                'league_id' => 1,
                'driver_id' => 52,
                'driver_number' => 99,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 53,
                'league_id' => 1,
                'driver_id' => 53,
                'driver_number' => 77,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 54,
                'league_id' => 1,
                'driver_id' => 54,
                'driver_number' => null,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 55,
                'league_id' => 1,
                'driver_id' => 55,
                'driver_number' => 123,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 56,
                'league_id' => 1,
                'driver_id' => 56,
                'driver_number' => null,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 57,
                'league_id' => 1,
                'driver_id' => 57,
                'driver_number' => 8,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 58,
                'league_id' => 1,
                'driver_id' => 58,
                'driver_number' => null,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 59,
                'league_id' => 1,
                'driver_id' => 59,
                'driver_number' => null,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 60,
                'league_id' => 1,
                'driver_id' => 60,
                'driver_number' => 95,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 61,
                'league_id' => 1,
                'driver_id' => 61,
                'driver_number' => 81,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 62,
                'league_id' => 1,
                'driver_id' => 62,
                'driver_number' => null,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 63,
                'league_id' => 1,
                'driver_id' => 63,
                'driver_number' => 3,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 64,
                'league_id' => 1,
                'driver_id' => 64,
                'driver_number' => null,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 65,
                'league_id' => 1,
                'driver_id' => 65,
                'driver_number' => 22,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 66,
                'league_id' => 1,
                'driver_id' => 66,
                'driver_number' => null,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 67,
                'league_id' => 1,
                'driver_id' => 67,
                'driver_number' => 33,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 68,
                'league_id' => 1,
                'driver_id' => 68,
                'driver_number' => 3,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 69,
                'league_id' => 1,
                'driver_id' => 69,
                'driver_number' => 28,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 70,
                'league_id' => 1,
                'driver_id' => 70,
                'driver_number' => 20,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 71,
                'league_id' => 1,
                'driver_id' => 71,
                'driver_number' => 52,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 72,
                'league_id' => 1,
                'driver_id' => 72,
                'driver_number' => 11,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 73,
                'league_id' => 1,
                'driver_id' => 73,
                'driver_number' => 2,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 74,
                'league_id' => 1,
                'driver_id' => 74,
                'driver_number' => 164,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 75,
                'league_id' => 1,
                'driver_id' => 75,
                'driver_number' => 24,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 76,
                'league_id' => 1,
                'driver_id' => 76,
                'driver_number' => 91,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 77,
                'league_id' => 1,
                'driver_id' => 77,
                'driver_number' => 7,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-02-04 03:10:10',
            ],
            [
                'id' => 78,
                'league_id' => 1,
                'driver_id' => 78,
                'driver_number' => 23,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 79,
                'league_id' => 1,
                'driver_id' => 79,
                'driver_number' => 14,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-01-20 12:27:05',
            ],
            [
                'id' => 80,
                'league_id' => 1,
                'driver_id' => 80,
                'driver_number' => 55,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-20 12:27:05',
                'updated_at' => '2026-02-04 03:08:35',
            ],
            [
                'id' => 84,
                'league_id' => 2,
                'driver_id' => 84,
                'driver_number' => null,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-22 10:04:41',
                'updated_at' => '2026-01-22 10:09:46',
            ],
            [
                'id' => 85,
                'league_id' => 2,
                'driver_id' => 85,
                'driver_number' => null,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-22 10:08:10',
                'updated_at' => '2026-01-22 10:09:53',
            ],
            [
                'id' => 86,
                'league_id' => 2,
                'driver_id' => 86,
                'driver_number' => null,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-22 10:09:40',
                'updated_at' => '2026-01-22 10:09:40',
            ],
            [
                'id' => 87,
                'league_id' => 2,
                'driver_id' => 87,
                'driver_number' => null,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-22 10:10:47',
                'updated_at' => '2026-01-22 10:10:47',
            ],
            [
                'id' => 88,
                'league_id' => 2,
                'driver_id' => 88,
                'driver_number' => null,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-22 10:11:06',
                'updated_at' => '2026-01-22 10:11:39',
            ],
            [
                'id' => 89,
                'league_id' => 2,
                'driver_id' => 89,
                'driver_number' => null,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-22 10:12:52',
                'updated_at' => '2026-01-22 10:12:52',
            ],
            [
                'id' => 90,
                'league_id' => 2,
                'driver_id' => 90,
                'driver_number' => null,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-22 10:18:36',
                'updated_at' => '2026-01-22 10:18:36',
            ],
            [
                'id' => 91,
                'league_id' => 2,
                'driver_id' => 91,
                'driver_number' => null,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-22 10:19:11',
                'updated_at' => '2026-01-22 10:19:57',
            ],
            [
                'id' => 92,
                'league_id' => 2,
                'driver_id' => 74,
                'driver_number' => null,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-25 07:25:10',
                'updated_at' => '2026-01-25 07:25:10',
            ],
            [
                'id' => 93,
                'league_id' => 1,
                'driver_id' => 92,
                'driver_number' => null,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-30 04:27:10',
                'updated_at' => '2026-01-30 04:27:10',
            ],
            [
                'id' => 94,
                'league_id' => 1,
                'driver_id' => 93,
                'driver_number' => null,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-30 04:28:35',
                'updated_at' => '2026-01-30 04:28:35',
            ],
            [
                'id' => 95,
                'league_id' => 1,
                'driver_id' => 94,
                'driver_number' => 6,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-30 04:29:30',
                'updated_at' => '2026-01-30 04:37:32',
            ],
            [
                'id' => 96,
                'league_id' => 1,
                'driver_id' => 95,
                'driver_number' => 47,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-30 04:29:44',
                'updated_at' => '2026-01-30 04:37:44',
            ],
            [
                'id' => 97,
                'league_id' => 1,
                'driver_id' => 96,
                'driver_number' => null,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-30 04:30:03',
                'updated_at' => '2026-01-30 04:36:36',
            ],
            [
                'id' => 98,
                'league_id' => 1,
                'driver_id' => 97,
                'driver_number' => null,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-30 04:33:40',
                'updated_at' => '2026-01-30 04:33:40',
            ],
            [
                'id' => 99,
                'league_id' => 1,
                'driver_id' => 98,
                'driver_number' => null,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-30 04:33:53',
                'updated_at' => '2026-01-30 04:33:53',
            ],
            [
                'id' => 100,
                'league_id' => 1,
                'driver_id' => 99,
                'driver_number' => null,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-30 04:34:09',
                'updated_at' => '2026-01-30 04:34:09',
            ],
            [
                'id' => 101,
                'league_id' => 1,
                'driver_id' => 100,
                'driver_number' => null,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-30 04:35:49',
                'updated_at' => '2026-01-30 04:36:15',
            ],
            [
                'id' => 102,
                'league_id' => 1,
                'driver_id' => 101,
                'driver_number' => 66,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-30 04:37:19',
                'updated_at' => '2026-01-30 04:37:19',
            ],
            [
                'id' => 103,
                'league_id' => 1,
                'driver_id' => 102,
                'driver_number' => null,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-30 04:37:55',
                'updated_at' => '2026-01-30 04:37:55',
            ],
            [
                'id' => 104,
                'league_id' => 1,
                'driver_id' => 103,
                'driver_number' => null,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-30 04:38:11',
                'updated_at' => '2026-01-30 04:38:11',
            ],
            [
                'id' => 105,
                'league_id' => 1,
                'driver_id' => 104,
                'driver_number' => null,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-30 04:38:26',
                'updated_at' => '2026-01-30 04:39:14',
            ],
            [
                'id' => 106,
                'league_id' => 1,
                'driver_id' => 105,
                'driver_number' => null,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-30 04:38:37',
                'updated_at' => '2026-01-30 04:39:08',
            ],
            [
                'id' => 107,
                'league_id' => 1,
                'driver_id' => 106,
                'driver_number' => null,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-30 04:38:53',
                'updated_at' => '2026-01-30 04:38:53',
            ],
            [
                'id' => 108,
                'league_id' => 1,
                'driver_id' => 107,
                'driver_number' => null,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-30 04:39:25',
                'updated_at' => '2026-01-30 04:39:25',
            ],
            [
                'id' => 109,
                'league_id' => 1,
                'driver_id' => 108,
                'driver_number' => 94,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-30 04:39:51',
                'updated_at' => '2026-01-30 04:39:51',
            ],
            [
                'id' => 110,
                'league_id' => 1,
                'driver_id' => 109,
                'driver_number' => null,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-30 04:41:59',
                'updated_at' => '2026-01-30 04:41:59',
            ],
            [
                'id' => 111,
                'league_id' => 1,
                'driver_id' => 110,
                'driver_number' => null,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-01-30 04:41:59',
                'updated_at' => '2026-01-30 04:41:59',
            ],
            [
                'id' => 112,
                'league_id' => 1,
                'driver_id' => 111,
                'driver_number' => null,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-04 03:00:24',
                'updated_at' => '2026-02-04 03:00:24',
            ],
            [
                'id' => 113,
                'league_id' => 1,
                'driver_id' => 112,
                'driver_number' => null,
                'status' => 'active',
                'league_notes' => null,
                'added_to_league_at' => '2026-02-04 03:02:04',
                'updated_at' => '2026-02-04 03:02:04',
            ],
        ];

        foreach ($league_drivers as $leagueDriversData) {
            LeagueDriverEloquent::updateOrCreate(
                ['id' => $leagueDriversData['id']],
                $leagueDriversData
            );
        }

        // Re-enable foreign key checks
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $this->command->info('LeagueDriversBackupSeeder seeded successfully. Total records: ' . count($league_drivers));
    }
}
