<?php

declare(strict_types=1);

namespace Database\Seeders\Backup;

use App\Infrastructure\Persistence\Eloquent\Models\Race;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * RacesBackupSeeder
 *
 * This seeder restores the races table data from a backup.
 * Generated: 2026-02-06
 *
 * IMPORTANT: This seeder should ONLY run in local/development/staging environments.
 * Dependencies: RoundsBackupSeeder must run first
 */
class RacesBackupSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Environment safety check - NEVER run in production
        if (app()->environment('production')) {
            $this->command->error('RacesBackupSeeder cannot run in production environment!');
            return;
        }

        $this->command->info('Seeding races backup data...');

        // Disable foreign key checks temporarily
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');

        $races = [
            [
                'id' => 1,
                'round_id' => 1,
                'is_qualifier' => true,
                'race_number' => null,
                'name' => null,
                'race_type' => null,
                'qualifying_format' => 'standard',
                'qualifying_length' => 10,
                'qualifying_tire' => null,
                'grid_source' => 'qualifying',
                'grid_source_race_id' => null,
                'length_type' => 'time',
                'length_value' => 10,
                'extra_lap_after_time' => false,
                'weather' => null,
                'tire_restrictions' => null,
                'fuel_usage' => null,
                'damage_model' => null,
                'track_limits_enforced' => false,
                'false_start_detection' => false,
                'collision_penalties' => false,
                'mandatory_pit_stop' => false,
                'minimum_pit_time' => null,
                'assists_restrictions' => null,
                'fastest_lap' => null,
                'fastest_lap_top_10' => false,
                'qualifying_pole' => null,
                'qualifying_pole_top_10' => false,
                'race_points' => true,
                'points_system' => json_encode('{"1":0}'),
                'dnf_points' => 0.00,
                'dns_points' => 0.00,
                'race_notes' => null,
                'status' => 'completed',
                'created_at' => '2025-11-27 11:33:10',
                'updated_at' => '2025-12-31 03:59:23',
            ],
            [
                'id' => 2,
                'round_id' => 1,
                'is_qualifier' => false,
                'race_number' => 1,
                'name' => null,
                'race_type' => 'feature',
                'qualifying_format' => 'none',
                'qualifying_length' => null,
                'qualifying_tire' => null,
                'grid_source' => 'qualifying',
                'grid_source_race_id' => 1,
                'length_type' => 'laps',
                'length_value' => 25,
                'extra_lap_after_time' => false,
                'weather' => null,
                'tire_restrictions' => null,
                'fuel_usage' => null,
                'damage_model' => null,
                'track_limits_enforced' => true,
                'false_start_detection' => true,
                'collision_penalties' => true,
                'mandatory_pit_stop' => false,
                'minimum_pit_time' => null,
                'assists_restrictions' => null,
                'fastest_lap' => null,
                'fastest_lap_top_10' => false,
                'qualifying_pole' => null,
                'qualifying_pole_top_10' => false,
                'race_points' => false,
                'points_system' => json_encode('{"1":25,"2":20,"3":16,"4":13,"5":11,"6":10,"7":9,"8":8,"9":7,"10":6,"11":5,"12":4,"13":3,"14":2,"15":1,"16":0}'),
                'dnf_points' => 0.00,
                'dns_points' => 0.00,
                'race_notes' => null,
                'status' => 'completed',
                'created_at' => '2025-11-27 11:51:26',
                'updated_at' => '2025-12-29 11:52:45',
            ],
            [
                'id' => 6,
                'round_id' => 4,
                'is_qualifier' => true,
                'race_number' => null,
                'name' => null,
                'race_type' => null,
                'qualifying_format' => 'standard',
                'qualifying_length' => 10,
                'qualifying_tire' => null,
                'grid_source' => 'qualifying',
                'grid_source_race_id' => null,
                'length_type' => 'time',
                'length_value' => 10,
                'extra_lap_after_time' => false,
                'weather' => null,
                'tire_restrictions' => null,
                'fuel_usage' => null,
                'damage_model' => null,
                'track_limits_enforced' => false,
                'false_start_detection' => false,
                'collision_penalties' => false,
                'mandatory_pit_stop' => false,
                'minimum_pit_time' => null,
                'assists_restrictions' => null,
                'fastest_lap' => null,
                'fastest_lap_top_10' => false,
                'qualifying_pole' => 1.00,
                'qualifying_pole_top_10' => false,
                'race_points' => false,
                'points_system' => json_encode('{"1":0}'),
                'dnf_points' => 0.00,
                'dns_points' => 0.00,
                'race_notes' => null,
                'status' => 'completed',
                'created_at' => '2025-12-02 10:08:34',
                'updated_at' => '2025-12-31 02:51:44',
            ],
            [
                'id' => 7,
                'round_id' => 4,
                'is_qualifier' => false,
                'race_number' => 1,
                'name' => null,
                'race_type' => 'sprint',
                'qualifying_format' => 'none',
                'qualifying_length' => null,
                'qualifying_tire' => null,
                'grid_source' => 'qualifying',
                'grid_source_race_id' => 6,
                'length_type' => 'laps',
                'length_value' => 9,
                'extra_lap_after_time' => false,
                'weather' => null,
                'tire_restrictions' => null,
                'fuel_usage' => null,
                'damage_model' => null,
                'track_limits_enforced' => true,
                'false_start_detection' => true,
                'collision_penalties' => true,
                'mandatory_pit_stop' => false,
                'minimum_pit_time' => null,
                'assists_restrictions' => null,
                'fastest_lap' => 1.00,
                'fastest_lap_top_10' => false,
                'qualifying_pole' => null,
                'qualifying_pole_top_10' => false,
                'race_points' => true,
                'points_system' => json_encode('{"1":25,"2":20,"3":16,"4":13,"5":11,"6":10,"7":9,"8":8,"9":7,"10":6,"11":5,"12":4,"13":3,"14":2,"15":1,"16":0}'),
                'dnf_points' => 0.00,
                'dns_points' => 0.00,
                'race_notes' => null,
                'status' => 'completed',
                'created_at' => '2025-12-02 10:09:33',
                'updated_at' => '2025-12-31 02:51:50',
            ],
            [
                'id' => 8,
                'round_id' => 4,
                'is_qualifier' => false,
                'race_number' => 2,
                'name' => null,
                'race_type' => 'sprint',
                'qualifying_format' => 'none',
                'qualifying_length' => null,
                'qualifying_tire' => null,
                'grid_source' => 'previous_race',
                'grid_source_race_id' => 7,
                'length_type' => 'laps',
                'length_value' => 9,
                'extra_lap_after_time' => false,
                'weather' => null,
                'tire_restrictions' => null,
                'fuel_usage' => null,
                'damage_model' => null,
                'track_limits_enforced' => true,
                'false_start_detection' => true,
                'collision_penalties' => true,
                'mandatory_pit_stop' => false,
                'minimum_pit_time' => null,
                'assists_restrictions' => null,
                'fastest_lap' => 1.00,
                'fastest_lap_top_10' => false,
                'qualifying_pole' => null,
                'qualifying_pole_top_10' => false,
                'race_points' => true,
                'points_system' => json_encode('{"1":25,"2":20,"3":16,"4":13,"5":11,"6":10,"7":9,"8":8,"9":7,"10":6,"11":5,"12":4,"13":3,"14":2,"15":1,"16":0}'),
                'dnf_points' => 0.00,
                'dns_points' => 0.00,
                'race_notes' => null,
                'status' => 'completed',
                'created_at' => '2025-12-02 10:09:47',
                'updated_at' => '2025-12-23 00:57:54',
            ],
            [
                'id' => 9,
                'round_id' => 4,
                'is_qualifier' => false,
                'race_number' => 3,
                'name' => null,
                'race_type' => 'sprint',
                'qualifying_format' => 'none',
                'qualifying_length' => null,
                'qualifying_tire' => null,
                'grid_source' => 'previous_race',
                'grid_source_race_id' => 8,
                'length_type' => 'laps',
                'length_value' => 9,
                'extra_lap_after_time' => false,
                'weather' => null,
                'tire_restrictions' => null,
                'fuel_usage' => null,
                'damage_model' => null,
                'track_limits_enforced' => true,
                'false_start_detection' => true,
                'collision_penalties' => true,
                'mandatory_pit_stop' => false,
                'minimum_pit_time' => null,
                'assists_restrictions' => null,
                'fastest_lap' => 1.00,
                'fastest_lap_top_10' => false,
                'qualifying_pole' => null,
                'qualifying_pole_top_10' => false,
                'race_points' => true,
                'points_system' => json_encode('{"1":25,"2":20,"3":16,"4":13,"5":11,"6":10,"7":9,"8":8,"9":7,"10":6,"11":5,"12":4,"13":3,"14":2,"15":1,"16":0}'),
                'dnf_points' => 0.00,
                'dns_points' => 0.00,
                'race_notes' => null,
                'status' => 'completed',
                'created_at' => '2025-12-02 10:10:01',
                'updated_at' => '2025-12-23 00:53:16',
            ],
            [
                'id' => 10,
                'round_id' => 5,
                'is_qualifier' => true,
                'race_number' => null,
                'name' => null,
                'race_type' => null,
                'qualifying_format' => 'standard',
                'qualifying_length' => 10,
                'qualifying_tire' => null,
                'grid_source' => 'qualifying',
                'grid_source_race_id' => null,
                'length_type' => 'time',
                'length_value' => 10,
                'extra_lap_after_time' => false,
                'weather' => null,
                'tire_restrictions' => null,
                'fuel_usage' => null,
                'damage_model' => null,
                'track_limits_enforced' => false,
                'false_start_detection' => false,
                'collision_penalties' => false,
                'mandatory_pit_stop' => false,
                'minimum_pit_time' => null,
                'assists_restrictions' => null,
                'fastest_lap' => null,
                'fastest_lap_top_10' => false,
                'qualifying_pole' => null,
                'qualifying_pole_top_10' => false,
                'race_points' => false,
                'points_system' => json_encode('{"1":0}'),
                'dnf_points' => 0.00,
                'dns_points' => 0.00,
                'race_notes' => null,
                'status' => 'completed',
                'created_at' => '2025-12-22 00:04:20',
                'updated_at' => '2026-01-01 03:51:43',
            ],
            [
                'id' => 11,
                'round_id' => 5,
                'is_qualifier' => false,
                'race_number' => 1,
                'name' => null,
                'race_type' => 'feature',
                'qualifying_format' => 'none',
                'qualifying_length' => null,
                'qualifying_tire' => null,
                'grid_source' => 'qualifying',
                'grid_source_race_id' => 10,
                'length_type' => 'laps',
                'length_value' => 29,
                'extra_lap_after_time' => false,
                'weather' => null,
                'tire_restrictions' => null,
                'fuel_usage' => null,
                'damage_model' => null,
                'track_limits_enforced' => true,
                'false_start_detection' => true,
                'collision_penalties' => true,
                'mandatory_pit_stop' => false,
                'minimum_pit_time' => null,
                'assists_restrictions' => null,
                'fastest_lap' => null,
                'fastest_lap_top_10' => false,
                'qualifying_pole' => null,
                'qualifying_pole_top_10' => false,
                'race_points' => false,
                'points_system' => json_encode('{"1":25,"2":18,"3":15,"4":12,"5":10,"6":8,"7":6,"8":4,"9":2,"10":1}'),
                'dnf_points' => 0.00,
                'dns_points' => 0.00,
                'race_notes' => null,
                'status' => 'completed',
                'created_at' => '2025-12-22 00:04:54',
                'updated_at' => '2025-12-23 12:04:23',
            ],
            [
                'id' => 12,
                'round_id' => 6,
                'is_qualifier' => true,
                'race_number' => null,
                'name' => null,
                'race_type' => null,
                'qualifying_format' => 'standard',
                'qualifying_length' => 10,
                'qualifying_tire' => null,
                'grid_source' => 'qualifying',
                'grid_source_race_id' => null,
                'length_type' => 'time',
                'length_value' => 10,
                'extra_lap_after_time' => false,
                'weather' => null,
                'tire_restrictions' => null,
                'fuel_usage' => null,
                'damage_model' => null,
                'track_limits_enforced' => false,
                'false_start_detection' => false,
                'collision_penalties' => false,
                'mandatory_pit_stop' => false,
                'minimum_pit_time' => null,
                'assists_restrictions' => null,
                'fastest_lap' => null,
                'fastest_lap_top_10' => false,
                'qualifying_pole' => null,
                'qualifying_pole_top_10' => false,
                'race_points' => false,
                'points_system' => json_encode('{"1":0}'),
                'dnf_points' => 0.00,
                'dns_points' => 0.00,
                'race_notes' => null,
                'status' => 'completed',
                'created_at' => '2025-12-22 00:05:47',
                'updated_at' => '2025-12-23 12:21:12',
            ],
            [
                'id' => 13,
                'round_id' => 6,
                'is_qualifier' => false,
                'race_number' => 1,
                'name' => null,
                'race_type' => 'feature',
                'qualifying_format' => 'none',
                'qualifying_length' => null,
                'qualifying_tire' => null,
                'grid_source' => 'qualifying',
                'grid_source_race_id' => 12,
                'length_type' => 'laps',
                'length_value' => 33,
                'extra_lap_after_time' => false,
                'weather' => null,
                'tire_restrictions' => null,
                'fuel_usage' => null,
                'damage_model' => null,
                'track_limits_enforced' => true,
                'false_start_detection' => true,
                'collision_penalties' => true,
                'mandatory_pit_stop' => false,
                'minimum_pit_time' => null,
                'assists_restrictions' => null,
                'fastest_lap' => null,
                'fastest_lap_top_10' => false,
                'qualifying_pole' => null,
                'qualifying_pole_top_10' => false,
                'race_points' => false,
                'points_system' => json_encode('{"1":25,"2":18,"3":15,"4":12,"5":10,"6":8,"7":6,"8":4,"9":2,"10":1}'),
                'dnf_points' => 0.00,
                'dns_points' => 0.00,
                'race_notes' => null,
                'status' => 'completed',
                'created_at' => '2025-12-22 00:06:06',
                'updated_at' => '2025-12-23 12:21:44',
            ],
            [
                'id' => 14,
                'round_id' => 7,
                'is_qualifier' => true,
                'race_number' => null,
                'name' => null,
                'race_type' => null,
                'qualifying_format' => 'standard',
                'qualifying_length' => 10,
                'qualifying_tire' => null,
                'grid_source' => 'qualifying',
                'grid_source_race_id' => null,
                'length_type' => 'time',
                'length_value' => 10,
                'extra_lap_after_time' => false,
                'weather' => null,
                'tire_restrictions' => null,
                'fuel_usage' => null,
                'damage_model' => null,
                'track_limits_enforced' => false,
                'false_start_detection' => false,
                'collision_penalties' => false,
                'mandatory_pit_stop' => false,
                'minimum_pit_time' => null,
                'assists_restrictions' => null,
                'fastest_lap' => null,
                'fastest_lap_top_10' => false,
                'qualifying_pole' => null,
                'qualifying_pole_top_10' => false,
                'race_points' => false,
                'points_system' => json_encode('{"1":0}'),
                'dnf_points' => 0.00,
                'dns_points' => 0.00,
                'race_notes' => null,
                'status' => 'completed',
                'created_at' => '2025-12-22 00:06:21',
                'updated_at' => '2025-12-24 09:58:15',
            ],
            [
                'id' => 15,
                'round_id' => 7,
                'is_qualifier' => false,
                'race_number' => 1,
                'name' => null,
                'race_type' => 'endurance',
                'qualifying_format' => 'none',
                'qualifying_length' => null,
                'qualifying_tire' => null,
                'grid_source' => 'qualifying',
                'grid_source_race_id' => 14,
                'length_type' => 'laps',
                'length_value' => 35,
                'extra_lap_after_time' => false,
                'weather' => null,
                'tire_restrictions' => null,
                'fuel_usage' => null,
                'damage_model' => null,
                'track_limits_enforced' => true,
                'false_start_detection' => true,
                'collision_penalties' => true,
                'mandatory_pit_stop' => false,
                'minimum_pit_time' => null,
                'assists_restrictions' => null,
                'fastest_lap' => null,
                'fastest_lap_top_10' => false,
                'qualifying_pole' => null,
                'qualifying_pole_top_10' => false,
                'race_points' => false,
                'points_system' => json_encode('{"1":25,"2":18,"3":15,"4":12,"5":10,"6":8,"7":6,"8":4,"9":2,"10":1}'),
                'dnf_points' => 0.00,
                'dns_points' => 0.00,
                'race_notes' => null,
                'status' => 'completed',
                'created_at' => '2025-12-22 00:06:44',
                'updated_at' => '2025-12-24 10:29:31',
            ],
            [
                'id' => 16,
                'round_id' => 8,
                'is_qualifier' => true,
                'race_number' => null,
                'name' => null,
                'race_type' => null,
                'qualifying_format' => 'standard',
                'qualifying_length' => 10,
                'qualifying_tire' => null,
                'grid_source' => 'qualifying',
                'grid_source_race_id' => null,
                'length_type' => 'time',
                'length_value' => 10,
                'extra_lap_after_time' => false,
                'weather' => null,
                'tire_restrictions' => null,
                'fuel_usage' => null,
                'damage_model' => null,
                'track_limits_enforced' => false,
                'false_start_detection' => false,
                'collision_penalties' => false,
                'mandatory_pit_stop' => false,
                'minimum_pit_time' => null,
                'assists_restrictions' => null,
                'fastest_lap' => null,
                'fastest_lap_top_10' => false,
                'qualifying_pole' => null,
                'qualifying_pole_top_10' => false,
                'race_points' => false,
                'points_system' => json_encode('{"1":0}'),
                'dnf_points' => 0.00,
                'dns_points' => 0.00,
                'race_notes' => null,
                'status' => 'completed',
                'created_at' => '2025-12-22 00:06:59',
                'updated_at' => '2025-12-26 06:31:54',
            ],
            [
                'id' => 17,
                'round_id' => 8,
                'is_qualifier' => false,
                'race_number' => 1,
                'name' => null,
                'race_type' => 'feature',
                'qualifying_format' => 'none',
                'qualifying_length' => null,
                'qualifying_tire' => null,
                'grid_source' => 'qualifying',
                'grid_source_race_id' => 16,
                'length_type' => 'laps',
                'length_value' => 20,
                'extra_lap_after_time' => false,
                'weather' => null,
                'tire_restrictions' => null,
                'fuel_usage' => null,
                'damage_model' => null,
                'track_limits_enforced' => true,
                'false_start_detection' => true,
                'collision_penalties' => true,
                'mandatory_pit_stop' => false,
                'minimum_pit_time' => null,
                'assists_restrictions' => null,
                'fastest_lap' => null,
                'fastest_lap_top_10' => false,
                'qualifying_pole' => null,
                'qualifying_pole_top_10' => false,
                'race_points' => false,
                'points_system' => json_encode('{"1":25,"2":18,"3":15,"4":12,"5":10,"6":8,"7":6,"8":4,"9":2,"10":1}'),
                'dnf_points' => 0.00,
                'dns_points' => 0.00,
                'race_notes' => null,
                'status' => 'completed',
                'created_at' => '2025-12-22 00:07:32',
                'updated_at' => '2025-12-26 06:31:56',
            ],
            [
                'id' => 18,
                'round_id' => 9,
                'is_qualifier' => true,
                'race_number' => null,
                'name' => null,
                'race_type' => null,
                'qualifying_format' => 'standard',
                'qualifying_length' => 10,
                'qualifying_tire' => null,
                'grid_source' => 'qualifying',
                'grid_source_race_id' => null,
                'length_type' => 'time',
                'length_value' => 10,
                'extra_lap_after_time' => false,
                'weather' => null,
                'tire_restrictions' => null,
                'fuel_usage' => null,
                'damage_model' => null,
                'track_limits_enforced' => false,
                'false_start_detection' => false,
                'collision_penalties' => false,
                'mandatory_pit_stop' => false,
                'minimum_pit_time' => null,
                'assists_restrictions' => null,
                'fastest_lap' => null,
                'fastest_lap_top_10' => false,
                'qualifying_pole' => null,
                'qualifying_pole_top_10' => false,
                'race_points' => false,
                'points_system' => json_encode('{"1":0}'),
                'dnf_points' => 0.00,
                'dns_points' => 0.00,
                'race_notes' => null,
                'status' => 'completed',
                'created_at' => '2025-12-22 00:07:47',
                'updated_at' => '2025-12-26 06:48:33',
            ],
            [
                'id' => 19,
                'round_id' => 9,
                'is_qualifier' => false,
                'race_number' => 1,
                'name' => null,
                'race_type' => 'sprint',
                'qualifying_format' => 'none',
                'qualifying_length' => null,
                'qualifying_tire' => null,
                'grid_source' => 'qualifying',
                'grid_source_race_id' => 18,
                'length_type' => 'laps',
                'length_value' => 20,
                'extra_lap_after_time' => false,
                'weather' => null,
                'tire_restrictions' => null,
                'fuel_usage' => null,
                'damage_model' => null,
                'track_limits_enforced' => true,
                'false_start_detection' => true,
                'collision_penalties' => true,
                'mandatory_pit_stop' => false,
                'minimum_pit_time' => null,
                'assists_restrictions' => null,
                'fastest_lap' => null,
                'fastest_lap_top_10' => false,
                'qualifying_pole' => null,
                'qualifying_pole_top_10' => false,
                'race_points' => true,
                'points_system' => json_encode('{"1":25,"2":20,"3":16,"4":13,"5":11,"6":10,"7":9,"8":8,"9":7,"10":6,"11":5,"12":4,"13":3,"14":2,"15":1,"16":0}'),
                'dnf_points' => 0.00,
                'dns_points' => 0.00,
                'race_notes' => null,
                'status' => 'completed',
                'created_at' => '2025-12-22 00:08:10',
                'updated_at' => '2025-12-28 12:35:03',
            ],
            [
                'id' => 20,
                'round_id' => 9,
                'is_qualifier' => false,
                'race_number' => 2,
                'name' => null,
                'race_type' => 'sprint',
                'qualifying_format' => 'none',
                'qualifying_length' => null,
                'qualifying_tire' => null,
                'grid_source' => 'reverse_previous',
                'grid_source_race_id' => 19,
                'length_type' => 'laps',
                'length_value' => 20,
                'extra_lap_after_time' => false,
                'weather' => null,
                'tire_restrictions' => null,
                'fuel_usage' => null,
                'damage_model' => null,
                'track_limits_enforced' => true,
                'false_start_detection' => true,
                'collision_penalties' => true,
                'mandatory_pit_stop' => false,
                'minimum_pit_time' => null,
                'assists_restrictions' => null,
                'fastest_lap' => null,
                'fastest_lap_top_10' => false,
                'qualifying_pole' => null,
                'qualifying_pole_top_10' => false,
                'race_points' => true,
                'points_system' => json_encode('{"1":12.5,"2":10,"3":8,"4":6.5,"5":5.5,"6":5,"7":4.5,"8":4,"9":3.5,"10":3,"11":2.5,"12":2,"13":1.5,"14":1,"15":0.5,"16":0}'),
                'dnf_points' => 0.00,
                'dns_points' => 0.00,
                'race_notes' => null,
                'status' => 'completed',
                'created_at' => '2025-12-22 00:09:01',
                'updated_at' => '2025-12-28 12:35:03',
            ],
        ];

        foreach ($races as $racesData) {
            Race::updateOrCreate(
                ['id' => $racesData['id']],
                $racesData
            );
        }

        // Re-enable foreign key checks
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $this->command->info('RacesBackupSeeder seeded successfully. Total records: ' . count($races));
    }
}
