<?php

declare(strict_types=1);

namespace Database\Seeders\Backup;

use App\Infrastructure\Persistence\Eloquent\Models\RaceResult;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Race Results Backup Seeder
 *
 * This seeder restores the race_results table data from a backup.
 * Generated: 2025-12-22
 *
 * IMPORTANT: This seeder should ONLY run in local/development/staging environments.
 * Dependencies: RacesBackupSeeder, SeasonDriversBackupSeeder, DivisionsBackupSeeder must run first
 */
class RaceResultsBackupSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Environment safety check - NEVER run in production
        if (app()->environment('production')) {
            $this->command->error('RaceResultsBackupSeeder cannot run in production environment!');
            return;
        }

        $this->command->info('Seeding race_results backup data...');

        // Disable foreign key checks temporarily
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');

        $raceResults = [
            [
                'id' => 1,
                'race_id' => 1,
                'driver_id' => 25,
                'division_id' => 1,
                'position' => 1,
                'original_race_time' => null,
                'original_race_time_difference' => null,
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:42.250',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:11',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 2,
                'race_id' => 1,
                'driver_id' => 76,
                'division_id' => 1,
                'position' => 2,
                'original_race_time' => null,
                'original_race_time_difference' => null,
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:42.475',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:11',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 3,
                'race_id' => 1,
                'driver_id' => 54,
                'division_id' => 1,
                'position' => 3,
                'original_race_time' => null,
                'original_race_time_difference' => null,
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:42.585',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:11',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 4,
                'race_id' => 1,
                'driver_id' => 52,
                'division_id' => 1,
                'position' => 4,
                'original_race_time' => null,
                'original_race_time_difference' => null,
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:42.724',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:11',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 5,
                'race_id' => 1,
                'driver_id' => 38,
                'division_id' => 1,
                'position' => 5,
                'original_race_time' => null,
                'original_race_time_difference' => null,
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:43.180',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:11',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 6,
                'race_id' => 1,
                'driver_id' => 16,
                'division_id' => 1,
                'position' => 6,
                'original_race_time' => null,
                'original_race_time_difference' => null,
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:43.401',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:11',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 7,
                'race_id' => 1,
                'driver_id' => 82,
                'division_id' => 1,
                'position' => 7,
                'original_race_time' => null,
                'original_race_time_difference' => null,
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:43.645',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:11',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 8,
                'race_id' => 1,
                'driver_id' => 73,
                'division_id' => 2,
                'position' => 1,
                'original_race_time' => null,
                'original_race_time_difference' => null,
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:43.546',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:11',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 9,
                'race_id' => 1,
                'driver_id' => 26,
                'division_id' => 2,
                'position' => 2,
                'original_race_time' => null,
                'original_race_time_difference' => null,
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:44.023',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:11',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 10,
                'race_id' => 1,
                'driver_id' => 60,
                'division_id' => 2,
                'position' => 3,
                'original_race_time' => null,
                'original_race_time_difference' => null,
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:44.112',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:11',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 11,
                'race_id' => 1,
                'driver_id' => 23,
                'division_id' => 2,
                'position' => 4,
                'original_race_time' => null,
                'original_race_time_difference' => null,
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:44.187',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:11',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 12,
                'race_id' => 1,
                'driver_id' => 15,
                'division_id' => 2,
                'position' => 5,
                'original_race_time' => null,
                'original_race_time_difference' => null,
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:44.405',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:11',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 13,
                'race_id' => 1,
                'driver_id' => 13,
                'division_id' => 2,
                'position' => 6,
                'original_race_time' => null,
                'original_race_time_difference' => null,
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:44.462',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:11',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 14,
                'race_id' => 1,
                'driver_id' => 77,
                'division_id' => 2,
                'position' => 7,
                'original_race_time' => null,
                'original_race_time_difference' => null,
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:44.474',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:11',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 15,
                'race_id' => 1,
                'driver_id' => 67,
                'division_id' => 2,
                'position' => 8,
                'original_race_time' => null,
                'original_race_time_difference' => null,
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:44.585',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:11',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 16,
                'race_id' => 1,
                'driver_id' => 37,
                'division_id' => 2,
                'position' => 9,
                'original_race_time' => null,
                'original_race_time_difference' => null,
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:44.620',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:11',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 17,
                'race_id' => 1,
                'driver_id' => 24,
                'division_id' => 2,
                'position' => 10,
                'original_race_time' => null,
                'original_race_time_difference' => null,
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:44.708',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:11',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 18,
                'race_id' => 1,
                'driver_id' => 40,
                'division_id' => 2,
                'position' => 11,
                'original_race_time' => null,
                'original_race_time_difference' => null,
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:44.829',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:11',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 19,
                'race_id' => 1,
                'driver_id' => 79,
                'division_id' => 2,
                'position' => 12,
                'original_race_time' => null,
                'original_race_time_difference' => null,
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:44.980',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:11',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 20,
                'race_id' => 1,
                'driver_id' => 6,
                'division_id' => 2,
                'position' => 13,
                'original_race_time' => null,
                'original_race_time_difference' => null,
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:45.011',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:11',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 21,
                'race_id' => 1,
                'driver_id' => 1,
                'division_id' => 2,
                'position' => 14,
                'original_race_time' => null,
                'original_race_time_difference' => null,
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:45.049',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:11',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 22,
                'race_id' => 1,
                'driver_id' => 64,
                'division_id' => 3,
                'position' => 1,
                'original_race_time' => null,
                'original_race_time_difference' => null,
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:44.184',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:11',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 23,
                'race_id' => 1,
                'driver_id' => 22,
                'division_id' => 3,
                'position' => 2,
                'original_race_time' => null,
                'original_race_time_difference' => null,
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:44.464',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:11',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 24,
                'race_id' => 1,
                'driver_id' => 2,
                'division_id' => 3,
                'position' => 3,
                'original_race_time' => null,
                'original_race_time_difference' => null,
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:44.602',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:11',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 25,
                'race_id' => 1,
                'driver_id' => 70,
                'division_id' => 3,
                'position' => 4,
                'original_race_time' => null,
                'original_race_time_difference' => null,
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:44.750',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:11',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 26,
                'race_id' => 1,
                'driver_id' => 66,
                'division_id' => 3,
                'position' => 5,
                'original_race_time' => null,
                'original_race_time_difference' => null,
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:44.802',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:11',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 27,
                'race_id' => 1,
                'driver_id' => 14,
                'division_id' => 3,
                'position' => 6,
                'original_race_time' => null,
                'original_race_time_difference' => null,
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:44.906',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:11',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 28,
                'race_id' => 1,
                'driver_id' => 59,
                'division_id' => 3,
                'position' => 7,
                'original_race_time' => null,
                'original_race_time_difference' => null,
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:44.931',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:11',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 29,
                'race_id' => 1,
                'driver_id' => 9,
                'division_id' => 3,
                'position' => 8,
                'original_race_time' => null,
                'original_race_time_difference' => null,
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:45.163',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:11',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 30,
                'race_id' => 1,
                'driver_id' => 51,
                'division_id' => 3,
                'position' => 9,
                'original_race_time' => null,
                'original_race_time_difference' => null,
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:45.240',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:11',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 31,
                'race_id' => 1,
                'driver_id' => 28,
                'division_id' => 3,
                'position' => 10,
                'original_race_time' => null,
                'original_race_time_difference' => null,
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:45.280',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:11',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 32,
                'race_id' => 1,
                'driver_id' => 30,
                'division_id' => 3,
                'position' => 11,
                'original_race_time' => null,
                'original_race_time_difference' => null,
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:45.700',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:11',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 33,
                'race_id' => 1,
                'driver_id' => 55,
                'division_id' => 3,
                'position' => 12,
                'original_race_time' => null,
                'original_race_time_difference' => null,
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:46.865',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:11',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 34,
                'race_id' => 1,
                'driver_id' => 74,
                'division_id' => 3,
                'position' => 13,
                'original_race_time' => null,
                'original_race_time_difference' => null,
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:46.995',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:11',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 35,
                'race_id' => 1,
                'driver_id' => 68,
                'division_id' => 4,
                'position' => 1,
                'original_race_time' => null,
                'original_race_time_difference' => null,
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:44.776',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:11',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 36,
                'race_id' => 1,
                'driver_id' => 43,
                'division_id' => 4,
                'position' => 2,
                'original_race_time' => null,
                'original_race_time_difference' => null,
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:45.139',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:11',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 37,
                'race_id' => 1,
                'driver_id' => 62,
                'division_id' => 4,
                'position' => 3,
                'original_race_time' => null,
                'original_race_time_difference' => null,
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:45.478',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:11',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 38,
                'race_id' => 1,
                'driver_id' => 50,
                'division_id' => 4,
                'position' => 4,
                'original_race_time' => null,
                'original_race_time_difference' => null,
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:45.873',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:11',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 39,
                'race_id' => 1,
                'driver_id' => 49,
                'division_id' => 4,
                'position' => 5,
                'original_race_time' => null,
                'original_race_time_difference' => null,
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:46.047',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:11',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 40,
                'race_id' => 1,
                'driver_id' => 45,
                'division_id' => 4,
                'position' => 6,
                'original_race_time' => null,
                'original_race_time_difference' => null,
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:46.055',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:11',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 41,
                'race_id' => 1,
                'driver_id' => 34,
                'division_id' => 4,
                'position' => 7,
                'original_race_time' => null,
                'original_race_time_difference' => null,
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:46.238',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:11',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 42,
                'race_id' => 1,
                'driver_id' => 3,
                'division_id' => 4,
                'position' => 8,
                'original_race_time' => null,
                'original_race_time_difference' => null,
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:46.554',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:11',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 43,
                'race_id' => 1,
                'driver_id' => 36,
                'division_id' => 4,
                'position' => 9,
                'original_race_time' => null,
                'original_race_time_difference' => null,
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:46.978',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:11',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 44,
                'race_id' => 1,
                'driver_id' => 17,
                'division_id' => 4,
                'position' => 10,
                'original_race_time' => null,
                'original_race_time_difference' => null,
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:47.929',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:11',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 45,
                'race_id' => 1,
                'driver_id' => 78,
                'division_id' => 4,
                'position' => 11,
                'original_race_time' => null,
                'original_race_time_difference' => null,
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:48.800',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:11',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 46,
                'race_id' => 2,
                'driver_id' => 25,
                'division_id' => 1,
                'position' => 1,
                'original_race_time' => '00:43:16.862',
                'original_race_time_difference' => null,
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:42.253',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:55',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 47,
                'race_id' => 2,
                'driver_id' => 54,
                'division_id' => 1,
                'position' => 2,
                'original_race_time' => '00:43:18.028',
                'original_race_time_difference' => '00:00:01.166',
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:42.378',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:55',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 48,
                'race_id' => 2,
                'driver_id' => 76,
                'division_id' => 1,
                'position' => 3,
                'original_race_time' => '00:43:23.126',
                'original_race_time_difference' => '00:00:06.264',
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:42.044',
                'penalties' => null,
                'has_fastest_lap' => true,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:55',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 49,
                'race_id' => 2,
                'driver_id' => 38,
                'division_id' => 1,
                'position' => 4,
                'original_race_time' => '00:43:43.451',
                'original_race_time_difference' => '00:00:26.589',
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:42.961',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:55',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 50,
                'race_id' => 2,
                'driver_id' => 52,
                'division_id' => 1,
                'position' => 5,
                'original_race_time' => '00:43:43.596',
                'original_race_time_difference' => '00:00:26.734',
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:42.744',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:55',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 51,
                'race_id' => 2,
                'driver_id' => 16,
                'division_id' => 1,
                'position' => 6,
                'original_race_time' => '00:43:45.823',
                'original_race_time_difference' => '00:00:28.961',
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:42.830',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:55',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 52,
                'race_id' => 2,
                'driver_id' => 82,
                'division_id' => 1,
                'position' => 7,
                'original_race_time' => null,
                'original_race_time_difference' => null,
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:43.695',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => true,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:55',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 53,
                'race_id' => 2,
                'driver_id' => 73,
                'division_id' => 2,
                'position' => 1,
                'original_race_time' => '00:44:00.470',
                'original_race_time_difference' => null,
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:43.856',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:55',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 54,
                'race_id' => 2,
                'driver_id' => 26,
                'division_id' => 2,
                'position' => 2,
                'original_race_time' => '00:44:01.084',
                'original_race_time_difference' => '00:00:00.614',
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:43.845',
                'penalties' => null,
                'has_fastest_lap' => true,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:55',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 55,
                'race_id' => 2,
                'driver_id' => 24,
                'division_id' => 2,
                'position' => 3,
                'original_race_time' => '00:44:07.948',
                'original_race_time_difference' => '00:00:07.478',
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:44.269',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:55',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 56,
                'race_id' => 2,
                'driver_id' => 13,
                'division_id' => 2,
                'position' => 4,
                'original_race_time' => '00:44:09.040',
                'original_race_time_difference' => '00:00:08.570',
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:44.115',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:55',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 57,
                'race_id' => 2,
                'driver_id' => 60,
                'division_id' => 2,
                'position' => 5,
                'original_race_time' => '00:44:09.415',
                'original_race_time_difference' => '00:00:08.945',
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:44.142',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:55',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 58,
                'race_id' => 2,
                'driver_id' => 15,
                'division_id' => 2,
                'position' => 6,
                'original_race_time' => '00:44:14.607',
                'original_race_time_difference' => '00:00:14.137',
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:44.232',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:55',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 59,
                'race_id' => 2,
                'driver_id' => 23,
                'division_id' => 2,
                'position' => 7,
                'original_race_time' => '00:44:19.271',
                'original_race_time_difference' => '00:00:18.801',
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:44.084',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:55',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 60,
                'race_id' => 2,
                'driver_id' => 67,
                'division_id' => 2,
                'position' => 8,
                'original_race_time' => '00:44:24.243',
                'original_race_time_difference' => '00:00:23.773',
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:44.569',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:55',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 61,
                'race_id' => 2,
                'driver_id' => 6,
                'division_id' => 2,
                'position' => 9,
                'original_race_time' => '00:44:27.103',
                'original_race_time_difference' => '00:00:26.633',
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:44.550',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:55',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 62,
                'race_id' => 2,
                'driver_id' => 77,
                'division_id' => 2,
                'position' => 10,
                'original_race_time' => '00:44:28.532',
                'original_race_time_difference' => '00:00:28.062',
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:44.208',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:55',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 63,
                'race_id' => 2,
                'driver_id' => 40,
                'division_id' => 2,
                'position' => 11,
                'original_race_time' => '00:44:28.828',
                'original_race_time_difference' => '00:00:28.358',
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:43.863',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:55',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 64,
                'race_id' => 2,
                'driver_id' => 1,
                'division_id' => 2,
                'position' => 12,
                'original_race_time' => '00:44:29.161',
                'original_race_time_difference' => '00:00:28.691',
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:44.303',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:55',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 65,
                'race_id' => 2,
                'driver_id' => 37,
                'division_id' => 2,
                'position' => 13,
                'original_race_time' => '00:44:35.227',
                'original_race_time_difference' => '00:00:34.757',
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:43.989',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:55',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 66,
                'race_id' => 2,
                'driver_id' => 79,
                'division_id' => 2,
                'position' => 14,
                'original_race_time' => '00:45:44.480',
                'original_race_time_difference' => '00:01:44.010',
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:44.645',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:55',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 67,
                'race_id' => 2,
                'driver_id' => 64,
                'division_id' => 3,
                'position' => 1,
                'original_race_time' => '00:44:10.193',
                'original_race_time_difference' => null,
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:44.067',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:55',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 68,
                'race_id' => 2,
                'driver_id' => 22,
                'division_id' => 3,
                'position' => 2,
                'original_race_time' => '00:44:15.265',
                'original_race_time_difference' => '00:00:05.072',
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:44.300',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:55',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 69,
                'race_id' => 2,
                'driver_id' => 70,
                'division_id' => 3,
                'position' => 3,
                'original_race_time' => '00:44:16.644',
                'original_race_time_difference' => '00:00:06.451',
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:44.297',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:55',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 70,
                'race_id' => 2,
                'driver_id' => 59,
                'division_id' => 3,
                'position' => 4,
                'original_race_time' => '00:44:23.780',
                'original_race_time_difference' => '00:00:13.587',
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:44.012',
                'penalties' => null,
                'has_fastest_lap' => true,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:55',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 71,
                'race_id' => 2,
                'driver_id' => 66,
                'division_id' => 3,
                'position' => 5,
                'original_race_time' => '00:44:29.863',
                'original_race_time_difference' => '00:00:19.670',
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:44.514',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:55',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 72,
                'race_id' => 2,
                'driver_id' => 2,
                'division_id' => 3,
                'position' => 6,
                'original_race_time' => '00:44:32.999',
                'original_race_time_difference' => '00:00:22.806',
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:44.834',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:55',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 73,
                'race_id' => 2,
                'driver_id' => 51,
                'division_id' => 3,
                'position' => 7,
                'original_race_time' => '00:44:33.172',
                'original_race_time_difference' => '00:00:22.979',
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:44.510',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:55',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 74,
                'race_id' => 2,
                'driver_id' => 9,
                'division_id' => 3,
                'position' => 8,
                'original_race_time' => '00:44:35.027',
                'original_race_time_difference' => '00:00:24.834',
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:44.165',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:55',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 75,
                'race_id' => 2,
                'driver_id' => 14,
                'division_id' => 3,
                'position' => 9,
                'original_race_time' => '00:44:45.317',
                'original_race_time_difference' => '00:00:35.124',
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:44.922',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:55',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 76,
                'race_id' => 2,
                'driver_id' => 30,
                'division_id' => 3,
                'position' => 10,
                'original_race_time' => '00:44:53.125',
                'original_race_time_difference' => '00:00:42.932',
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:44.598',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:55',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 77,
                'race_id' => 2,
                'driver_id' => 55,
                'division_id' => 3,
                'position' => 11,
                'original_race_time' => '00:44:59.296',
                'original_race_time_difference' => '00:00:49.103',
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:45.190',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:55',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 78,
                'race_id' => 2,
                'driver_id' => 28,
                'division_id' => 3,
                'position' => 12,
                'original_race_time' => '00:45:00.294',
                'original_race_time_difference' => '00:00:50.101',
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:44.748',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:55',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 79,
                'race_id' => 2,
                'driver_id' => 74,
                'division_id' => 3,
                'position' => 13,
                'original_race_time' => '00:45:27.062',
                'original_race_time_difference' => '00:01:16.869',
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:46.010',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:55',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 80,
                'race_id' => 2,
                'driver_id' => 68,
                'division_id' => 4,
                'position' => 1,
                'original_race_time' => '00:44:23.113',
                'original_race_time_difference' => null,
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:44.276',
                'penalties' => null,
                'has_fastest_lap' => true,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:55',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 81,
                'race_id' => 2,
                'driver_id' => 43,
                'division_id' => 4,
                'position' => 2,
                'original_race_time' => '00:44:43.459',
                'original_race_time_difference' => '00:00:20.346',
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:44.836',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:55',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 82,
                'race_id' => 2,
                'driver_id' => 62,
                'division_id' => 4,
                'position' => 3,
                'original_race_time' => '00:44:48.379',
                'original_race_time_difference' => '00:00:25.266',
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:45.469',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:55',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 83,
                'race_id' => 2,
                'driver_id' => 50,
                'division_id' => 4,
                'position' => 4,
                'original_race_time' => '00:45:01.105',
                'original_race_time_difference' => '00:00:37.992',
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:44.307',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:55',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 84,
                'race_id' => 2,
                'driver_id' => 45,
                'division_id' => 4,
                'position' => 5,
                'original_race_time' => '00:45:02.360',
                'original_race_time_difference' => '00:00:39.247',
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:45.874',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:55',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 85,
                'race_id' => 2,
                'driver_id' => 49,
                'division_id' => 4,
                'position' => 6,
                'original_race_time' => '00:45:03.763',
                'original_race_time_difference' => '00:00:40.650',
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:44.909',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:55',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 86,
                'race_id' => 2,
                'driver_id' => 34,
                'division_id' => 4,
                'position' => 7,
                'original_race_time' => '00:45:09.782',
                'original_race_time_difference' => '00:00:46.669',
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:45.675',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:55',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 87,
                'race_id' => 2,
                'driver_id' => 17,
                'division_id' => 4,
                'position' => 8,
                'original_race_time' => '00:45:48.793',
                'original_race_time_difference' => '00:01:25.680',
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:46.820',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:55',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 88,
                'race_id' => 2,
                'driver_id' => 36,
                'division_id' => 4,
                'position' => 9,
                'original_race_time' => '00:46:09.912',
                'original_race_time_difference' => '00:01:46.799',
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:45.699',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:55',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 89,
                'race_id' => 2,
                'driver_id' => 78,
                'division_id' => 4,
                'position' => 10,
                'original_race_time' => '00:46:10.923',
                'original_race_time_difference' => '00:01:47.810',
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:47.810',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => false,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:55',
                'updated_at' => '2025-12-22 05:04:56',
            ],
            [
                'id' => 90,
                'race_id' => 2,
                'driver_id' => 3,
                'division_id' => 4,
                'position' => 11,
                'original_race_time' => null,
                'original_race_time_difference' => null,
                'final_race_time_difference' => null,
                'fastest_lap' => '00:01:46.726',
                'penalties' => null,
                'has_fastest_lap' => false,
                'has_pole' => false,
                'dnf' => true,
                'status' => 'confirmed',
                'race_points' => 0,
                'positions_gained' => null,
                'created_at' => '2025-12-22 05:04:55',
                'updated_at' => '2025-12-22 05:04:56',
            ],
        ];

        foreach ($raceResults as $resultData) {
            RaceResult::updateOrCreate(
                ['id' => $resultData['id']],
                $resultData
            );
        }

        // Re-enable foreign key checks
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $this->command->info('Race results backup seeded successfully. Total records: ' . count($raceResults));
    }
}
