<?php

declare(strict_types=1);

namespace Database\Seeders\Backup;

use App\Infrastructure\Persistence\Eloquent\Models\SeasonDriverEloquent;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * SeasonDriversBackupSeeder
 *
 * This seeder restores the season_drivers table data from a backup.
 * Generated: 2026-02-07
 *
 * IMPORTANT: This seeder should ONLY run in local/development/staging environments.
 * Dependencies: SeasonsBackupSeeder, LeagueDriversBackupSeeder, TeamsBackupSeeder, DivisionsBackupSeeder must run first
 */
class SeasonDriversBackupSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Environment safety check - NEVER run in production
        if (app()->environment('production')) {
            $this->command->error('SeasonDriversBackupSeeder cannot run in production environment!');
            return;
        }

        $this->command->info('Seeding season_drivers backup data...');

        // Disable foreign key checks temporarily
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');

        $season_drivers = [
            [
                'id' => 1,
                'season_id' => 4,
                'league_driver_id' => 7,
                'team_id' => 2,
                'division_id' => 2,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:36:43',
                'updated_at' => '2025-12-22 05:11:48',
            ],
            [
                'id' => 2,
                'season_id' => 4,
                'league_driver_id' => 39,
                'team_id' => 2,
                'division_id' => 3,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:36:44',
                'updated_at' => '2025-12-22 05:12:03',
            ],
            [
                'id' => 3,
                'season_id' => 4,
                'league_driver_id' => 66,
                'team_id' => 3,
                'division_id' => 4,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:36:45',
                'updated_at' => '2025-12-22 05:14:19',
            ],
            [
                'id' => 5,
                'season_id' => 4,
                'league_driver_id' => 67,
                'team_id' => null,
                'division_id' => 4,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:36:46',
                'updated_at' => '2025-12-22 04:39:06',
            ],
            [
                'id' => 6,
                'season_id' => 4,
                'league_driver_id' => 62,
                'team_id' => null,
                'division_id' => 2,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:36:46',
                'updated_at' => '2025-12-22 04:39:39',
            ],
            [
                'id' => 9,
                'season_id' => 4,
                'league_driver_id' => 5,
                'team_id' => null,
                'division_id' => 3,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:36:47',
                'updated_at' => '2025-12-22 04:39:28',
            ],
            [
                'id' => 12,
                'season_id' => 4,
                'league_driver_id' => 28,
                'team_id' => 3,
                'division_id' => 4,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:36:49',
                'updated_at' => '2025-12-22 05:14:11',
            ],
            [
                'id' => 13,
                'season_id' => 4,
                'league_driver_id' => 22,
                'team_id' => 2,
                'division_id' => 2,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:36:50',
                'updated_at' => '2025-12-22 05:11:55',
            ],
            [
                'id' => 14,
                'season_id' => 4,
                'league_driver_id' => 23,
                'team_id' => null,
                'division_id' => 3,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:36:50',
                'updated_at' => '2025-12-22 04:40:50',
            ],
            [
                'id' => 15,
                'season_id' => 4,
                'league_driver_id' => 51,
                'team_id' => null,
                'division_id' => 2,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:36:51',
                'updated_at' => '2025-12-22 04:40:53',
            ],
            [
                'id' => 16,
                'season_id' => 4,
                'league_driver_id' => 56,
                'team_id' => 3,
                'division_id' => 1,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:36:51',
                'updated_at' => '2025-12-22 05:13:16',
            ],
            [
                'id' => 17,
                'season_id' => 4,
                'league_driver_id' => 18,
                'team_id' => 2,
                'division_id' => 4,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:36:51',
                'updated_at' => '2025-12-22 05:13:00',
            ],
            [
                'id' => 20,
                'season_id' => 4,
                'league_driver_id' => 45,
                'team_id' => 3,
                'division_id' => 3,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:36:53',
                'updated_at' => '2025-12-22 05:13:45',
            ],
            [
                'id' => 22,
                'season_id' => 4,
                'league_driver_id' => 34,
                'team_id' => null,
                'division_id' => 3,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:36:54',
                'updated_at' => '2025-12-22 04:41:55',
            ],
            [
                'id' => 23,
                'season_id' => 4,
                'league_driver_id' => 44,
                'team_id' => 1,
                'division_id' => 2,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:36:54',
                'updated_at' => '2025-12-22 05:16:08',
            ],
            [
                'id' => 24,
                'season_id' => 4,
                'league_driver_id' => 63,
                'team_id' => null,
                'division_id' => 2,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:36:55',
                'updated_at' => '2025-12-22 04:42:15',
            ],
            [
                'id' => 25,
                'season_id' => 4,
                'league_driver_id' => 41,
                'team_id' => null,
                'division_id' => 1,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:36:55',
                'updated_at' => '2025-12-22 04:42:13',
            ],
            [
                'id' => 26,
                'season_id' => 4,
                'league_driver_id' => 9,
                'team_id' => null,
                'division_id' => 2,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:36:58',
                'updated_at' => '2025-12-22 04:42:21',
            ],
            [
                'id' => 27,
                'season_id' => 4,
                'league_driver_id' => 20,
                'team_id' => 1,
                'division_id' => 4,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:36:58',
                'updated_at' => '2025-12-22 05:18:31',
            ],
            [
                'id' => 28,
                'season_id' => 4,
                'league_driver_id' => 47,
                'team_id' => 2,
                'division_id' => 3,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:36:59',
                'updated_at' => '2025-12-22 05:12:11',
            ],
            [
                'id' => 30,
                'season_id' => 4,
                'league_driver_id' => 1,
                'team_id' => null,
                'division_id' => 3,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:00',
                'updated_at' => '2025-12-22 04:49:45',
            ],
            [
                'id' => 31,
                'season_id' => 4,
                'league_driver_id' => 68,
                'team_id' => null,
                'division_id' => 4,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:01',
                'updated_at' => '2025-12-22 04:49:49',
            ],
            [
                'id' => 33,
                'season_id' => 4,
                'league_driver_id' => 53,
                'team_id' => null,
                'division_id' => 4,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:02',
                'updated_at' => '2025-12-22 04:50:04',
            ],
            [
                'id' => 34,
                'season_id' => 4,
                'league_driver_id' => 10,
                'team_id' => 2,
                'division_id' => 4,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:03',
                'updated_at' => '2025-12-22 05:12:37',
            ],
            [
                'id' => 35,
                'season_id' => 4,
                'league_driver_id' => 12,
                'team_id' => 2,
                'division_id' => 4,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:03',
                'updated_at' => '2025-12-22 05:12:53',
            ],
            [
                'id' => 36,
                'season_id' => 4,
                'league_driver_id' => 26,
                'team_id' => 2,
                'division_id' => 4,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:04',
                'updated_at' => '2025-12-22 05:12:45',
            ],
            [
                'id' => 37,
                'season_id' => 4,
                'league_driver_id' => 64,
                'team_id' => 1,
                'division_id' => 2,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:04',
                'updated_at' => '2025-12-22 05:16:15',
            ],
            [
                'id' => 38,
                'season_id' => 4,
                'league_driver_id' => 55,
                'team_id' => null,
                'division_id' => 1,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:05',
                'updated_at' => '2025-12-22 04:51:52',
            ],
            [
                'id' => 40,
                'season_id' => 4,
                'league_driver_id' => 15,
                'team_id' => 3,
                'division_id' => 2,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:07',
                'updated_at' => '2025-12-22 05:14:37',
            ],
            [
                'id' => 43,
                'season_id' => 4,
                'league_driver_id' => 8,
                'team_id' => 2,
                'division_id' => 4,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:08',
                'updated_at' => '2025-12-22 05:12:20',
            ],
            [
                'id' => 45,
                'season_id' => 4,
                'league_driver_id' => 49,
                'team_id' => 3,
                'division_id' => 4,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:09',
                'updated_at' => '2025-12-22 05:14:00',
            ],
            [
                'id' => 47,
                'season_id' => 4,
                'league_driver_id' => 60,
                'team_id' => 1,
                'division_id' => 2,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:11',
                'updated_at' => '2025-12-22 05:15:59',
            ],
            [
                'id' => 48,
                'season_id' => 4,
                'league_driver_id' => 57,
                'team_id' => null,
                'division_id' => 1,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:12',
                'updated_at' => '2025-12-22 04:49:03',
            ],
            [
                'id' => 49,
                'season_id' => 4,
                'league_driver_id' => 14,
                'team_id' => 1,
                'division_id' => 4,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:13',
                'updated_at' => '2025-12-22 05:18:13',
            ],
            [
                'id' => 50,
                'season_id' => 4,
                'league_driver_id' => 48,
                'team_id' => 1,
                'division_id' => 4,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:13',
                'updated_at' => '2025-12-22 05:18:22',
            ],
            [
                'id' => 51,
                'season_id' => 4,
                'league_driver_id' => 50,
                'team_id' => null,
                'division_id' => 3,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:14',
                'updated_at' => '2025-12-22 04:48:23',
            ],
            [
                'id' => 52,
                'season_id' => 4,
                'league_driver_id' => 29,
                'team_id' => 3,
                'division_id' => 1,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:15',
                'updated_at' => '2025-12-22 05:13:10',
            ],
            [
                'id' => 53,
                'season_id' => 4,
                'league_driver_id' => 11,
                'team_id' => 1,
                'division_id' => 4,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:16',
                'updated_at' => '2025-12-22 05:18:36',
            ],
            [
                'id' => 54,
                'season_id' => 4,
                'league_driver_id' => 16,
                'team_id' => null,
                'division_id' => 1,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:17',
                'updated_at' => '2025-12-22 04:47:53',
            ],
            [
                'id' => 55,
                'season_id' => 4,
                'league_driver_id' => 17,
                'team_id' => null,
                'division_id' => 3,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:18',
                'updated_at' => '2025-12-22 04:47:51',
            ],
            [
                'id' => 58,
                'season_id' => 4,
                'league_driver_id' => 13,
                'team_id' => null,
                'division_id' => 3,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:21',
                'updated_at' => '2025-12-22 04:47:17',
            ],
            [
                'id' => 59,
                'season_id' => 4,
                'league_driver_id' => 36,
                'team_id' => null,
                'division_id' => 3,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:23',
                'updated_at' => '2025-12-22 04:47:11',
            ],
            [
                'id' => 60,
                'season_id' => 4,
                'league_driver_id' => 61,
                'team_id' => 3,
                'division_id' => 2,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:24',
                'updated_at' => '2025-12-22 05:13:25',
            ],
            [
                'id' => 62,
                'season_id' => 4,
                'league_driver_id' => 46,
                'team_id' => 3,
                'division_id' => 4,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:26',
                'updated_at' => '2025-12-22 05:14:27',
            ],
            [
                'id' => 63,
                'season_id' => 4,
                'league_driver_id' => 59,
                'team_id' => null,
                'division_id' => 1,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:26',
                'updated_at' => '2025-12-22 04:46:38',
            ],
            [
                'id' => 64,
                'season_id' => 4,
                'league_driver_id' => 37,
                'team_id' => null,
                'division_id' => 3,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:27',
                'updated_at' => '2025-12-22 04:46:29',
            ],
            [
                'id' => 65,
                'season_id' => 4,
                'league_driver_id' => 30,
                'team_id' => null,
                'division_id' => 2,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:28',
                'updated_at' => '2025-12-22 04:46:22',
            ],
            [
                'id' => 66,
                'season_id' => 4,
                'league_driver_id' => 40,
                'team_id' => 1,
                'division_id' => 3,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:29',
                'updated_at' => '2025-12-22 05:16:26',
            ],
            [
                'id' => 67,
                'season_id' => 4,
                'league_driver_id' => 32,
                'team_id' => null,
                'division_id' => 2,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:30',
                'updated_at' => '2025-12-22 04:46:15',
            ],
            [
                'id' => 68,
                'season_id' => 4,
                'league_driver_id' => 24,
                'team_id' => null,
                'division_id' => 3,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:31',
                'updated_at' => '2025-12-22 23:47:38',
            ],
            [
                'id' => 69,
                'season_id' => 4,
                'league_driver_id' => 2,
                'team_id' => 1,
                'division_id' => 3,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:32',
                'updated_at' => '2025-12-22 05:17:51',
            ],
            [
                'id' => 70,
                'season_id' => 4,
                'league_driver_id' => 43,
                'team_id' => 3,
                'division_id' => 3,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:32',
                'updated_at' => '2025-12-22 05:13:53',
            ],
            [
                'id' => 72,
                'season_id' => 4,
                'league_driver_id' => 33,
                'team_id' => 1,
                'division_id' => 3,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:34',
                'updated_at' => '2025-12-22 05:18:08',
            ],
            [
                'id' => 73,
                'season_id' => 4,
                'league_driver_id' => 27,
                'team_id' => 2,
                'division_id' => 2,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:35',
                'updated_at' => '2025-12-22 05:11:42',
            ],
            [
                'id' => 74,
                'season_id' => 4,
                'league_driver_id' => 3,
                'team_id' => null,
                'division_id' => 4,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:37',
                'updated_at' => '2025-12-22 23:31:32',
            ],
            [
                'id' => 75,
                'season_id' => 4,
                'league_driver_id' => 54,
                'team_id' => 2,
                'division_id' => 1,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:38',
                'updated_at' => '2025-12-22 05:11:36',
            ],
            [
                'id' => 76,
                'season_id' => 4,
                'league_driver_id' => 25,
                'team_id' => null,
                'division_id' => 1,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:39',
                'updated_at' => '2025-12-22 04:43:58',
            ],
            [
                'id' => 77,
                'season_id' => 4,
                'league_driver_id' => 35,
                'team_id' => 3,
                'division_id' => 2,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:40',
                'updated_at' => '2025-12-22 05:13:37',
            ],
            [
                'id' => 78,
                'season_id' => 4,
                'league_driver_id' => 21,
                'team_id' => null,
                'division_id' => 4,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:41',
                'updated_at' => '2025-12-22 04:43:36',
            ],
            [
                'id' => 79,
                'season_id' => 4,
                'league_driver_id' => 31,
                'team_id' => 1,
                'division_id' => 3,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:42',
                'updated_at' => '2025-12-22 23:31:26',
            ],
            [
                'id' => 81,
                'season_id' => 4,
                'league_driver_id' => 65,
                'team_id' => null,
                'division_id' => 2,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:45:26',
                'updated_at' => '2025-12-22 04:45:43',
            ],
            [
                'id' => 82,
                'season_id' => 4,
                'league_driver_id' => 58,
                'team_id' => 1,
                'division_id' => 1,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:54:25',
                'updated_at' => '2025-12-22 05:15:53',
            ],
            [
                'id' => 84,
                'season_id' => 5,
                'league_driver_id' => 91,
                'team_id' => null,
                'division_id' => null,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-01-22 10:38:39',
                'updated_at' => '2026-01-22 10:38:39',
            ],
            [
                'id' => 85,
                'season_id' => 5,
                'league_driver_id' => 85,
                'team_id' => null,
                'division_id' => null,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-01-22 10:38:40',
                'updated_at' => '2026-01-22 10:38:40',
            ],
            [
                'id' => 86,
                'season_id' => 5,
                'league_driver_id' => 90,
                'team_id' => null,
                'division_id' => null,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-01-22 10:38:40',
                'updated_at' => '2026-01-22 10:38:40',
            ],
            [
                'id' => 87,
                'season_id' => 5,
                'league_driver_id' => 87,
                'team_id' => null,
                'division_id' => null,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-01-22 10:38:41',
                'updated_at' => '2026-01-22 10:38:41',
            ],
            [
                'id' => 88,
                'season_id' => 5,
                'league_driver_id' => 86,
                'team_id' => null,
                'division_id' => null,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-01-22 10:38:42',
                'updated_at' => '2026-01-22 10:38:42',
            ],
            [
                'id' => 89,
                'season_id' => 5,
                'league_driver_id' => 88,
                'team_id' => null,
                'division_id' => null,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-01-22 10:38:43',
                'updated_at' => '2026-01-22 10:38:43',
            ],
            [
                'id' => 90,
                'season_id' => 5,
                'league_driver_id' => 89,
                'team_id' => null,
                'division_id' => null,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-01-22 10:38:43',
                'updated_at' => '2026-01-22 10:38:43',
            ],
            [
                'id' => 92,
                'season_id' => 5,
                'league_driver_id' => 84,
                'team_id' => null,
                'division_id' => null,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-01-25 05:44:39',
                'updated_at' => '2026-01-25 05:44:39',
            ],
            [
                'id' => 93,
                'season_id' => 6,
                'league_driver_id' => 104,
                'team_id' => null,
                'division_id' => 6,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-01-30 04:43:58',
                'updated_at' => '2026-02-03 12:21:45',
            ],
            [
                'id' => 94,
                'season_id' => 6,
                'league_driver_id' => 103,
                'team_id' => null,
                'division_id' => 6,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-01-30 04:44:04',
                'updated_at' => '2026-02-03 12:21:32',
            ],
            [
                'id' => 95,
                'season_id' => 6,
                'league_driver_id' => 71,
                'team_id' => null,
                'division_id' => 8,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-01-30 04:44:09',
                'updated_at' => '2026-02-03 12:21:16',
            ],
            [
                'id' => 96,
                'season_id' => 6,
                'league_driver_id' => 75,
                'team_id' => 4,
                'division_id' => 9,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-01-30 04:44:17',
                'updated_at' => '2026-02-03 12:29:55',
            ],
            [
                'id' => 97,
                'season_id' => 6,
                'league_driver_id' => 101,
                'team_id' => null,
                'division_id' => 8,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-01-30 04:44:26',
                'updated_at' => '2026-02-03 12:16:28',
            ],
            [
                'id' => 98,
                'season_id' => 6,
                'league_driver_id' => 3,
                'team_id' => null,
                'division_id' => 9,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-01-30 04:44:37',
                'updated_at' => '2026-01-30 04:47:42',
            ],
            [
                'id' => 99,
                'season_id' => 6,
                'league_driver_id' => 21,
                'team_id' => null,
                'division_id' => 9,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-01-30 04:44:43',
                'updated_at' => '2026-01-30 04:47:45',
            ],
            [
                'id' => 100,
                'season_id' => 6,
                'league_driver_id' => 49,
                'team_id' => 5,
                'division_id' => 9,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-01-30 04:44:50',
                'updated_at' => '2026-02-03 12:31:29',
            ],
            [
                'id' => 101,
                'season_id' => 6,
                'league_driver_id' => 48,
                'team_id' => 4,
                'division_id' => 9,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-01-30 04:45:17',
                'updated_at' => '2026-02-03 12:30:12',
            ],
            [
                'id' => 102,
                'season_id' => 6,
                'league_driver_id' => 20,
                'team_id' => 4,
                'division_id' => 9,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-01-30 04:45:34',
                'updated_at' => '2026-02-03 12:31:16',
            ],
            [
                'id' => 103,
                'season_id' => 6,
                'league_driver_id' => 66,
                'team_id' => 5,
                'division_id' => 9,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-01-30 04:45:40',
                'updated_at' => '2026-02-03 12:30:59',
            ],
            [
                'id' => 104,
                'season_id' => 6,
                'league_driver_id' => 26,
                'team_id' => 7,
                'division_id' => 9,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-01-30 04:45:44',
                'updated_at' => '2026-02-03 12:30:54',
            ],
            [
                'id' => 105,
                'season_id' => 6,
                'league_driver_id' => 10,
                'team_id' => 6,
                'division_id' => 9,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-01-30 04:46:30',
                'updated_at' => '2026-02-03 12:31:11',
            ],
            [
                'id' => 106,
                'season_id' => 6,
                'league_driver_id' => 12,
                'team_id' => 6,
                'division_id' => 9,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-01-30 04:46:33',
                'updated_at' => '2026-02-03 12:30:17',
            ],
            [
                'id' => 108,
                'season_id' => 6,
                'league_driver_id' => 70,
                'team_id' => null,
                'division_id' => 9,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-01-30 05:02:55',
                'updated_at' => '2026-02-03 12:18:57',
            ],
            [
                'id' => 109,
                'season_id' => 6,
                'league_driver_id' => 108,
                'team_id' => 5,
                'division_id' => 9,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-01-30 05:03:19',
                'updated_at' => '2026-02-03 12:31:37',
            ],
            [
                'id' => 110,
                'season_id' => 6,
                'league_driver_id' => 109,
                'team_id' => null,
                'division_id' => 8,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-01-30 05:03:24',
                'updated_at' => '2026-01-30 05:14:39',
            ],
            [
                'id' => 112,
                'season_id' => 6,
                'league_driver_id' => 68,
                'team_id' => 4,
                'division_id' => 8,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-01-30 05:04:03',
                'updated_at' => '2026-02-03 12:32:11',
            ],
            [
                'id' => 113,
                'season_id' => 6,
                'league_driver_id' => 47,
                'team_id' => 6,
                'division_id' => 8,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-01-30 05:04:09',
                'updated_at' => '2026-02-03 12:32:35',
            ],
            [
                'id' => 114,
                'season_id' => 6,
                'league_driver_id' => 34,
                'team_id' => null,
                'division_id' => 7,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-01-30 05:04:15',
                'updated_at' => '2026-02-03 12:22:27',
            ],
            [
                'id' => 115,
                'season_id' => 6,
                'league_driver_id' => 74,
                'team_id' => 7,
                'division_id' => 8,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-01-30 05:04:34',
                'updated_at' => '2026-02-03 12:32:07',
            ],
            [
                'id' => 116,
                'season_id' => 6,
                'league_driver_id' => 107,
                'team_id' => null,
                'division_id' => 7,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-01-30 05:04:56',
                'updated_at' => '2026-02-03 12:23:53',
            ],
            [
                'id' => 117,
                'season_id' => 6,
                'league_driver_id' => 40,
                'team_id' => 4,
                'division_id' => 8,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-01-30 05:05:01',
                'updated_at' => '2026-02-03 12:32:29',
            ],
            [
                'id' => 118,
                'season_id' => 6,
                'league_driver_id' => 39,
                'team_id' => 6,
                'division_id' => 8,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-01-30 05:05:08',
                'updated_at' => '2026-02-03 12:32:22',
            ],
            [
                'id' => 119,
                'season_id' => 6,
                'league_driver_id' => 102,
                'team_id' => 7,
                'division_id' => 8,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-01-30 05:05:13',
                'updated_at' => '2026-02-03 12:32:40',
            ],
            [
                'id' => 121,
                'season_id' => 6,
                'league_driver_id' => 14,
                'team_id' => 4,
                'division_id' => 7,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-01-30 05:05:28',
                'updated_at' => '2026-02-03 12:32:57',
            ],
            [
                'id' => 122,
                'season_id' => 6,
                'league_driver_id' => 24,
                'team_id' => null,
                'division_id' => 8,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-02-03 12:14:27',
                'updated_at' => '2026-02-03 12:14:42',
            ],
            [
                'id' => 123,
                'season_id' => 6,
                'league_driver_id' => 36,
                'team_id' => null,
                'division_id' => 8,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-02-03 12:16:56',
                'updated_at' => '2026-02-03 12:17:03',
            ],
            [
                'id' => 125,
                'season_id' => 6,
                'league_driver_id' => 17,
                'team_id' => null,
                'division_id' => 8,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-02-03 12:17:30',
                'updated_at' => '2026-02-03 12:17:40',
            ],
            [
                'id' => 126,
                'season_id' => 6,
                'league_driver_id' => 46,
                'team_id' => 5,
                'division_id' => 9,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-02-03 12:18:07',
                'updated_at' => '2026-02-03 12:30:08',
            ],
            [
                'id' => 127,
                'season_id' => 6,
                'league_driver_id' => 28,
                'team_id' => 7,
                'division_id' => 9,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-02-03 12:19:49',
                'updated_at' => '2026-02-03 12:31:21',
            ],
            [
                'id' => 128,
                'season_id' => 6,
                'league_driver_id' => 18,
                'team_id' => 6,
                'division_id' => 9,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-02-03 12:20:51',
                'updated_at' => '2026-02-03 12:30:48',
            ],
            [
                'id' => 129,
                'season_id' => 6,
                'league_driver_id' => 22,
                'team_id' => 6,
                'division_id' => 7,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-02-03 12:25:44',
                'updated_at' => '2026-02-03 12:33:03',
            ],
            [
                'id' => 130,
                'season_id' => 6,
                'league_driver_id' => 1,
                'team_id' => null,
                'division_id' => 7,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-02-03 12:25:48',
                'updated_at' => '2026-02-03 12:27:13',
            ],
            [
                'id' => 131,
                'season_id' => 6,
                'league_driver_id' => 5,
                'team_id' => null,
                'division_id' => 7,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-02-03 12:25:53',
                'updated_at' => '2026-02-03 12:27:07',
            ],
            [
                'id' => 132,
                'season_id' => 6,
                'league_driver_id' => 45,
                'team_id' => 7,
                'division_id' => 7,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-02-03 12:25:57',
                'updated_at' => '2026-02-03 12:33:09',
            ],
            [
                'id' => 133,
                'season_id' => 6,
                'league_driver_id' => 15,
                'team_id' => 5,
                'division_id' => 7,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-02-03 12:26:06',
                'updated_at' => '2026-02-03 12:33:17',
            ],
            [
                'id' => 134,
                'season_id' => 6,
                'league_driver_id' => 43,
                'team_id' => 5,
                'division_id' => 7,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-02-03 12:26:11',
                'updated_at' => '2026-02-03 12:33:36',
            ],
            [
                'id' => 135,
                'season_id' => 6,
                'league_driver_id' => 50,
                'team_id' => null,
                'division_id' => 7,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-02-03 12:26:16',
                'updated_at' => '2026-02-03 12:27:18',
            ],
            [
                'id' => 136,
                'season_id' => 6,
                'league_driver_id' => 32,
                'team_id' => null,
                'division_id' => 7,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-02-03 12:26:21',
                'updated_at' => '2026-02-03 12:27:22',
            ],
            [
                'id' => 137,
                'season_id' => 6,
                'league_driver_id' => 31,
                'team_id' => 7,
                'division_id' => 7,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-02-03 12:26:27',
                'updated_at' => '2026-02-03 12:34:13',
            ],
            [
                'id' => 138,
                'season_id' => 6,
                'league_driver_id' => 2,
                'team_id' => 4,
                'division_id' => 7,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-02-03 12:26:33',
                'updated_at' => '2026-02-03 12:33:46',
            ],
            [
                'id' => 139,
                'season_id' => 6,
                'league_driver_id' => 33,
                'team_id' => 4,
                'division_id' => 7,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-02-03 12:26:38',
                'updated_at' => '2026-02-03 12:33:50',
            ],
            [
                'id' => 140,
                'season_id' => 6,
                'league_driver_id' => 60,
                'team_id' => 4,
                'division_id' => 7,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-02-03 12:26:44',
                'updated_at' => '2026-02-03 12:33:57',
            ],
            [
                'id' => 141,
                'season_id' => 6,
                'league_driver_id' => 7,
                'team_id' => 6,
                'division_id' => 7,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-02-03 12:26:49',
                'updated_at' => '2026-02-03 12:34:17',
            ],
            [
                'id' => 142,
                'season_id' => 6,
                'league_driver_id' => 61,
                'team_id' => 5,
                'division_id' => 6,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-02-03 12:38:28',
                'updated_at' => '2026-02-03 12:40:16',
            ],
            [
                'id' => 143,
                'season_id' => 6,
                'league_driver_id' => 63,
                'team_id' => null,
                'division_id' => 6,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-02-03 12:38:33',
                'updated_at' => '2026-02-03 12:39:59',
            ],
            [
                'id' => 144,
                'season_id' => 6,
                'league_driver_id' => 9,
                'team_id' => null,
                'division_id' => 6,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-02-03 12:38:37',
                'updated_at' => '2026-02-03 12:40:01',
            ],
            [
                'id' => 145,
                'season_id' => 6,
                'league_driver_id' => 27,
                'team_id' => 6,
                'division_id' => 6,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-02-03 12:38:42',
                'updated_at' => '2026-02-03 12:40:21',
            ],
            [
                'id' => 146,
                'season_id' => 6,
                'league_driver_id' => 35,
                'team_id' => 5,
                'division_id' => 6,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-02-03 12:38:48',
                'updated_at' => '2026-02-03 12:40:26',
            ],
            [
                'id' => 147,
                'season_id' => 6,
                'league_driver_id' => 44,
                'team_id' => 4,
                'division_id' => 6,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-02-03 12:38:53',
                'updated_at' => '2026-02-03 12:40:31',
            ],
            [
                'id' => 148,
                'season_id' => 6,
                'league_driver_id' => 51,
                'team_id' => null,
                'division_id' => 6,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-02-03 12:39:00',
                'updated_at' => '2026-02-03 12:39:56',
            ],
            [
                'id' => 149,
                'season_id' => 6,
                'league_driver_id' => 72,
                'team_id' => 7,
                'division_id' => 6,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-02-03 12:39:05',
                'updated_at' => '2026-02-03 12:40:35',
            ],
            [
                'id' => 150,
                'season_id' => 6,
                'league_driver_id' => 99,
                'team_id' => null,
                'division_id' => 6,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-02-03 12:39:10',
                'updated_at' => '2026-02-03 12:39:51',
            ],
            [
                'id' => 151,
                'season_id' => 6,
                'league_driver_id' => 105,
                'team_id' => null,
                'division_id' => 6,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-02-03 12:39:19',
                'updated_at' => '2026-02-03 12:40:05',
            ],
            [
                'id' => 152,
                'season_id' => 6,
                'league_driver_id' => 106,
                'team_id' => null,
                'division_id' => 6,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-02-03 12:39:29',
                'updated_at' => '2026-02-03 12:40:03',
            ],
            [
                'id' => 153,
                'season_id' => 6,
                'league_driver_id' => 23,
                'team_id' => null,
                'division_id' => 6,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-02-03 12:39:35',
                'updated_at' => '2026-02-03 12:39:54',
            ],
            [
                'id' => 154,
                'season_id' => 6,
                'league_driver_id' => 67,
                'team_id' => null,
                'division_id' => 6,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-02-03 12:39:40',
                'updated_at' => '2026-02-03 12:39:49',
            ],
            [
                'id' => 155,
                'season_id' => 6,
                'league_driver_id' => 112,
                'team_id' => null,
                'division_id' => 8,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-02-04 03:11:21',
                'updated_at' => '2026-02-04 03:16:45',
            ],
            [
                'id' => 156,
                'season_id' => 6,
                'league_driver_id' => 113,
                'team_id' => null,
                'division_id' => 6,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-02-04 03:11:31',
                'updated_at' => '2026-02-04 03:15:32',
            ],
            [
                'id' => 157,
                'season_id' => 6,
                'league_driver_id' => 54,
                'team_id' => 7,
                'division_id' => 5,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-02-04 03:11:36',
                'updated_at' => '2026-02-04 03:17:21',
            ],
            [
                'id' => 158,
                'season_id' => 6,
                'league_driver_id' => 56,
                'team_id' => 5,
                'division_id' => 5,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-02-04 03:11:40',
                'updated_at' => '2026-02-04 03:17:34',
            ],
            [
                'id' => 159,
                'season_id' => 6,
                'league_driver_id' => 4,
                'team_id' => 6,
                'division_id' => 5,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-02-04 03:11:48',
                'updated_at' => '2026-02-04 03:17:28',
            ],
            [
                'id' => 160,
                'season_id' => 6,
                'league_driver_id' => 16,
                'team_id' => null,
                'division_id' => 5,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-02-04 03:11:49',
                'updated_at' => '2026-02-04 03:16:30',
            ],
            [
                'id' => 161,
                'season_id' => 6,
                'league_driver_id' => 98,
                'team_id' => null,
                'division_id' => 5,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-02-04 03:11:56',
                'updated_at' => '2026-02-04 03:15:03',
            ],
            [
                'id' => 162,
                'season_id' => 6,
                'league_driver_id' => 69,
                'team_id' => 4,
                'division_id' => 5,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-02-04 03:12:08',
                'updated_at' => '2026-02-04 03:17:49',
            ],
            [
                'id' => 163,
                'season_id' => 6,
                'league_driver_id' => 80,
                'team_id' => null,
                'division_id' => 5,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-02-04 03:12:17',
                'updated_at' => '2026-02-04 03:15:29',
            ],
            [
                'id' => 164,
                'season_id' => 6,
                'league_driver_id' => 100,
                'team_id' => null,
                'division_id' => 5,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-02-04 03:12:40',
                'updated_at' => '2026-02-04 03:17:06',
            ],
            [
                'id' => 165,
                'season_id' => 6,
                'league_driver_id' => 55,
                'team_id' => null,
                'division_id' => 5,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-02-04 03:12:45',
                'updated_at' => '2026-02-04 03:16:08',
            ],
            [
                'id' => 166,
                'season_id' => 6,
                'league_driver_id' => 19,
                'team_id' => null,
                'division_id' => 5,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-02-04 03:13:01',
                'updated_at' => '2026-02-04 03:15:22',
            ],
            [
                'id' => 167,
                'season_id' => 6,
                'league_driver_id' => 111,
                'team_id' => null,
                'division_id' => 8,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-02-04 03:13:32',
                'updated_at' => '2026-02-04 03:14:16',
            ],
            [
                'id' => 168,
                'season_id' => 6,
                'league_driver_id' => 29,
                'team_id' => null,
                'division_id' => 5,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-02-04 03:13:37',
                'updated_at' => '2026-02-04 03:16:26',
            ],
            [
                'id' => 169,
                'season_id' => 6,
                'league_driver_id' => 77,
                'team_id' => null,
                'division_id' => 5,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-02-04 03:13:39',
                'updated_at' => '2026-02-04 03:16:23',
            ],
            [
                'id' => 170,
                'season_id' => 6,
                'league_driver_id' => 57,
                'team_id' => null,
                'division_id' => 5,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-02-04 03:13:41',
                'updated_at' => '2026-02-04 03:16:20',
            ],
            [
                'id' => 171,
                'season_id' => 6,
                'league_driver_id' => 6,
                'team_id' => null,
                'division_id' => 5,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-02-04 03:13:46',
                'updated_at' => '2026-02-04 03:16:18',
            ],
            [
                'id' => 172,
                'season_id' => 6,
                'league_driver_id' => 30,
                'team_id' => 4,
                'division_id' => 5,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-02-04 03:13:54',
                'updated_at' => '2026-02-04 03:17:40',
            ],
            [
                'id' => 173,
                'season_id' => 6,
                'league_driver_id' => 25,
                'team_id' => null,
                'division_id' => 5,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-02-04 03:14:00',
                'updated_at' => '2026-02-04 03:16:40',
            ],
            [
                'id' => 174,
                'season_id' => 6,
                'league_driver_id' => 8,
                'team_id' => 6,
                'division_id' => 8,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-02-04 03:22:23',
                'updated_at' => '2026-02-04 03:22:37',
            ],
            [
                'id' => 175,
                'season_id' => 6,
                'league_driver_id' => 62,
                'team_id' => null,
                'division_id' => null,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-02-04 03:30:04',
                'updated_at' => '2026-02-04 03:30:04',
            ],
            [
                'id' => 177,
                'season_id' => 6,
                'league_driver_id' => 38,
                'team_id' => null,
                'division_id' => null,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2026-02-04 03:30:13',
                'updated_at' => '2026-02-04 03:30:13',
            ],
        ];

        foreach ($season_drivers as $seasonDriversData) {
            SeasonDriverEloquent::updateOrCreate(
                ['id' => $seasonDriversData['id']],
                $seasonDriversData
            );
        }

        // Re-enable foreign key checks
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $this->command->info('SeasonDriversBackupSeeder seeded successfully. Total records: ' . count($season_drivers));
    }
}
