<?php

declare(strict_types=1);

namespace Database\Seeders\Backup;

use App\Infrastructure\Persistence\Eloquent\Models\SeasonDriverEloquent;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * SeasonDriversBackupSeeder
 *
 * This seeder restores the season_drivers table data from a backup.
 * Generated: 2026-01-07
 *
 * IMPORTANT: This seeder should ONLY run in local/development/staging environments.
 * Dependencies: SeasonsBackupSeeder, TeamsBackupSeeder, DivisionsBackupSeeder must run first
 */
class SeasonDriversBackupSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Environment safety check - NEVER run in production
        if (app()->environment('production')) {
            $this->command->error('SeasonDriversBackupSeeder cannot run in production environment!');
            return;
        }

        $this->command->info('Seeding season_drivers backup data...');

        // Disable foreign key checks temporarily
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');

        $season_drivers = [
            [
                'id' => 1,
                'season_id' => 4,
                'league_driver_id' => 7,
                'team_id' => 2,
                'division_id' => 2,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:36:43',
                'updated_at' => '2025-12-22 05:11:48',
            ],
            [
                'id' => 2,
                'season_id' => 4,
                'league_driver_id' => 39,
                'team_id' => 2,
                'division_id' => 3,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:36:44',
                'updated_at' => '2025-12-22 05:12:03',
            ],
            [
                'id' => 3,
                'season_id' => 4,
                'league_driver_id' => 66,
                'team_id' => 3,
                'division_id' => 4,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:36:45',
                'updated_at' => '2025-12-22 05:14:19',
            ],
            [
                'id' => 5,
                'season_id' => 4,
                'league_driver_id' => 67,
                'team_id' => null,
                'division_id' => 4,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:36:46',
                'updated_at' => '2025-12-22 04:39:06',
            ],
            [
                'id' => 6,
                'season_id' => 4,
                'league_driver_id' => 62,
                'team_id' => null,
                'division_id' => 2,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:36:46',
                'updated_at' => '2025-12-22 04:39:39',
            ],
            [
                'id' => 9,
                'season_id' => 4,
                'league_driver_id' => 5,
                'team_id' => null,
                'division_id' => 3,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:36:47',
                'updated_at' => '2025-12-22 04:39:28',
            ],
            [
                'id' => 12,
                'season_id' => 4,
                'league_driver_id' => 28,
                'team_id' => 3,
                'division_id' => 4,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:36:49',
                'updated_at' => '2025-12-22 05:14:11',
            ],
            [
                'id' => 13,
                'season_id' => 4,
                'league_driver_id' => 22,
                'team_id' => 2,
                'division_id' => 2,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:36:50',
                'updated_at' => '2025-12-22 05:11:55',
            ],
            [
                'id' => 14,
                'season_id' => 4,
                'league_driver_id' => 23,
                'team_id' => null,
                'division_id' => 3,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:36:50',
                'updated_at' => '2025-12-22 04:40:50',
            ],
            [
                'id' => 15,
                'season_id' => 4,
                'league_driver_id' => 51,
                'team_id' => null,
                'division_id' => 2,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:36:51',
                'updated_at' => '2025-12-22 04:40:53',
            ],
            [
                'id' => 16,
                'season_id' => 4,
                'league_driver_id' => 56,
                'team_id' => 3,
                'division_id' => 1,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:36:51',
                'updated_at' => '2025-12-22 05:13:16',
            ],
            [
                'id' => 17,
                'season_id' => 4,
                'league_driver_id' => 18,
                'team_id' => 2,
                'division_id' => 4,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:36:51',
                'updated_at' => '2025-12-22 05:13:00',
            ],
            [
                'id' => 20,
                'season_id' => 4,
                'league_driver_id' => 45,
                'team_id' => 3,
                'division_id' => 3,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:36:53',
                'updated_at' => '2025-12-22 05:13:45',
            ],
            [
                'id' => 22,
                'season_id' => 4,
                'league_driver_id' => 34,
                'team_id' => null,
                'division_id' => 3,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:36:54',
                'updated_at' => '2025-12-22 04:41:55',
            ],
            [
                'id' => 23,
                'season_id' => 4,
                'league_driver_id' => 44,
                'team_id' => 1,
                'division_id' => 2,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:36:54',
                'updated_at' => '2025-12-22 05:16:08',
            ],
            [
                'id' => 24,
                'season_id' => 4,
                'league_driver_id' => 63,
                'team_id' => null,
                'division_id' => 2,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:36:55',
                'updated_at' => '2025-12-22 04:42:15',
            ],
            [
                'id' => 25,
                'season_id' => 4,
                'league_driver_id' => 41,
                'team_id' => null,
                'division_id' => 1,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:36:55',
                'updated_at' => '2025-12-22 04:42:13',
            ],
            [
                'id' => 26,
                'season_id' => 4,
                'league_driver_id' => 9,
                'team_id' => null,
                'division_id' => 2,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:36:58',
                'updated_at' => '2025-12-22 04:42:21',
            ],
            [
                'id' => 27,
                'season_id' => 4,
                'league_driver_id' => 20,
                'team_id' => 1,
                'division_id' => 4,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:36:58',
                'updated_at' => '2025-12-22 05:18:31',
            ],
            [
                'id' => 28,
                'season_id' => 4,
                'league_driver_id' => 47,
                'team_id' => 2,
                'division_id' => 3,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:36:59',
                'updated_at' => '2025-12-22 05:12:11',
            ],
            [
                'id' => 30,
                'season_id' => 4,
                'league_driver_id' => 1,
                'team_id' => null,
                'division_id' => 3,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:00',
                'updated_at' => '2025-12-22 04:49:45',
            ],
            [
                'id' => 31,
                'season_id' => 4,
                'league_driver_id' => 68,
                'team_id' => null,
                'division_id' => 4,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:01',
                'updated_at' => '2025-12-22 04:49:49',
            ],
            [
                'id' => 33,
                'season_id' => 4,
                'league_driver_id' => 53,
                'team_id' => null,
                'division_id' => 4,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:02',
                'updated_at' => '2025-12-22 04:50:04',
            ],
            [
                'id' => 34,
                'season_id' => 4,
                'league_driver_id' => 10,
                'team_id' => 2,
                'division_id' => 4,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:03',
                'updated_at' => '2025-12-22 05:12:37',
            ],
            [
                'id' => 35,
                'season_id' => 4,
                'league_driver_id' => 12,
                'team_id' => 2,
                'division_id' => 4,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:03',
                'updated_at' => '2025-12-22 05:12:53',
            ],
            [
                'id' => 36,
                'season_id' => 4,
                'league_driver_id' => 26,
                'team_id' => 2,
                'division_id' => 4,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:04',
                'updated_at' => '2025-12-22 05:12:45',
            ],
            [
                'id' => 37,
                'season_id' => 4,
                'league_driver_id' => 64,
                'team_id' => 1,
                'division_id' => 2,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:04',
                'updated_at' => '2025-12-22 05:16:15',
            ],
            [
                'id' => 38,
                'season_id' => 4,
                'league_driver_id' => 55,
                'team_id' => null,
                'division_id' => 1,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:05',
                'updated_at' => '2025-12-22 04:51:52',
            ],
            [
                'id' => 40,
                'season_id' => 4,
                'league_driver_id' => 15,
                'team_id' => 3,
                'division_id' => 2,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:07',
                'updated_at' => '2025-12-22 05:14:37',
            ],
            [
                'id' => 43,
                'season_id' => 4,
                'league_driver_id' => 8,
                'team_id' => 2,
                'division_id' => 4,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:08',
                'updated_at' => '2025-12-22 05:12:20',
            ],
            [
                'id' => 45,
                'season_id' => 4,
                'league_driver_id' => 49,
                'team_id' => 3,
                'division_id' => 4,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:09',
                'updated_at' => '2025-12-22 05:14:00',
            ],
            [
                'id' => 47,
                'season_id' => 4,
                'league_driver_id' => 60,
                'team_id' => 1,
                'division_id' => 2,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:11',
                'updated_at' => '2025-12-22 05:15:59',
            ],
            [
                'id' => 48,
                'season_id' => 4,
                'league_driver_id' => 57,
                'team_id' => null,
                'division_id' => 1,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:12',
                'updated_at' => '2025-12-22 04:49:03',
            ],
            [
                'id' => 49,
                'season_id' => 4,
                'league_driver_id' => 14,
                'team_id' => 1,
                'division_id' => 4,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:13',
                'updated_at' => '2025-12-22 05:18:13',
            ],
            [
                'id' => 50,
                'season_id' => 4,
                'league_driver_id' => 48,
                'team_id' => 1,
                'division_id' => 4,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:13',
                'updated_at' => '2025-12-22 05:18:22',
            ],
            [
                'id' => 51,
                'season_id' => 4,
                'league_driver_id' => 50,
                'team_id' => null,
                'division_id' => 3,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:14',
                'updated_at' => '2025-12-22 04:48:23',
            ],
            [
                'id' => 52,
                'season_id' => 4,
                'league_driver_id' => 29,
                'team_id' => 3,
                'division_id' => 1,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:15',
                'updated_at' => '2025-12-22 05:13:10',
            ],
            [
                'id' => 53,
                'season_id' => 4,
                'league_driver_id' => 11,
                'team_id' => 1,
                'division_id' => 4,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:16',
                'updated_at' => '2025-12-22 05:18:36',
            ],
            [
                'id' => 54,
                'season_id' => 4,
                'league_driver_id' => 16,
                'team_id' => null,
                'division_id' => 1,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:17',
                'updated_at' => '2025-12-22 04:47:53',
            ],
            [
                'id' => 55,
                'season_id' => 4,
                'league_driver_id' => 17,
                'team_id' => null,
                'division_id' => 3,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:18',
                'updated_at' => '2025-12-22 04:47:51',
            ],
            [
                'id' => 58,
                'season_id' => 4,
                'league_driver_id' => 13,
                'team_id' => null,
                'division_id' => 3,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:21',
                'updated_at' => '2025-12-22 04:47:17',
            ],
            [
                'id' => 59,
                'season_id' => 4,
                'league_driver_id' => 36,
                'team_id' => null,
                'division_id' => 3,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:23',
                'updated_at' => '2025-12-22 04:47:11',
            ],
            [
                'id' => 60,
                'season_id' => 4,
                'league_driver_id' => 61,
                'team_id' => 3,
                'division_id' => 2,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:24',
                'updated_at' => '2025-12-22 05:13:25',
            ],
            [
                'id' => 62,
                'season_id' => 4,
                'league_driver_id' => 46,
                'team_id' => 3,
                'division_id' => 4,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:26',
                'updated_at' => '2025-12-22 05:14:27',
            ],
            [
                'id' => 63,
                'season_id' => 4,
                'league_driver_id' => 59,
                'team_id' => null,
                'division_id' => 1,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:26',
                'updated_at' => '2025-12-22 04:46:38',
            ],
            [
                'id' => 64,
                'season_id' => 4,
                'league_driver_id' => 37,
                'team_id' => null,
                'division_id' => 3,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:27',
                'updated_at' => '2025-12-22 04:46:29',
            ],
            [
                'id' => 65,
                'season_id' => 4,
                'league_driver_id' => 30,
                'team_id' => null,
                'division_id' => 2,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:28',
                'updated_at' => '2025-12-22 04:46:22',
            ],
            [
                'id' => 66,
                'season_id' => 4,
                'league_driver_id' => 40,
                'team_id' => 1,
                'division_id' => 3,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:29',
                'updated_at' => '2025-12-22 05:16:26',
            ],
            [
                'id' => 67,
                'season_id' => 4,
                'league_driver_id' => 32,
                'team_id' => null,
                'division_id' => 2,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:30',
                'updated_at' => '2025-12-22 04:46:15',
            ],
            [
                'id' => 68,
                'season_id' => 4,
                'league_driver_id' => 24,
                'team_id' => null,
                'division_id' => 3,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:31',
                'updated_at' => '2025-12-22 23:47:38',
            ],
            [
                'id' => 69,
                'season_id' => 4,
                'league_driver_id' => 2,
                'team_id' => 1,
                'division_id' => 3,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:32',
                'updated_at' => '2025-12-22 05:17:51',
            ],
            [
                'id' => 70,
                'season_id' => 4,
                'league_driver_id' => 43,
                'team_id' => 3,
                'division_id' => 3,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:32',
                'updated_at' => '2025-12-22 05:13:53',
            ],
            [
                'id' => 72,
                'season_id' => 4,
                'league_driver_id' => 33,
                'team_id' => 1,
                'division_id' => 3,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:34',
                'updated_at' => '2025-12-22 05:18:08',
            ],
            [
                'id' => 73,
                'season_id' => 4,
                'league_driver_id' => 27,
                'team_id' => 2,
                'division_id' => 2,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:35',
                'updated_at' => '2025-12-22 05:11:42',
            ],
            [
                'id' => 74,
                'season_id' => 4,
                'league_driver_id' => 3,
                'team_id' => null,
                'division_id' => 4,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:37',
                'updated_at' => '2025-12-22 23:31:32',
            ],
            [
                'id' => 75,
                'season_id' => 4,
                'league_driver_id' => 54,
                'team_id' => 2,
                'division_id' => 1,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:38',
                'updated_at' => '2025-12-22 05:11:36',
            ],
            [
                'id' => 76,
                'season_id' => 4,
                'league_driver_id' => 25,
                'team_id' => null,
                'division_id' => 1,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:39',
                'updated_at' => '2025-12-22 04:43:58',
            ],
            [
                'id' => 77,
                'season_id' => 4,
                'league_driver_id' => 35,
                'team_id' => 3,
                'division_id' => 2,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:40',
                'updated_at' => '2025-12-22 05:13:37',
            ],
            [
                'id' => 78,
                'season_id' => 4,
                'league_driver_id' => 21,
                'team_id' => null,
                'division_id' => 4,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:41',
                'updated_at' => '2025-12-22 04:43:36',
            ],
            [
                'id' => 79,
                'season_id' => 4,
                'league_driver_id' => 31,
                'team_id' => 1,
                'division_id' => 3,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:37:42',
                'updated_at' => '2025-12-22 23:31:26',
            ],
            [
                'id' => 81,
                'season_id' => 4,
                'league_driver_id' => 65,
                'team_id' => null,
                'division_id' => 2,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:45:26',
                'updated_at' => '2025-12-22 04:45:43',
            ],
            [
                'id' => 82,
                'season_id' => 4,
                'league_driver_id' => 58,
                'team_id' => 1,
                'division_id' => 1,
                'status' => 'active',
                'notes' => null,
                'added_at' => '2025-12-22 04:54:25',
                'updated_at' => '2025-12-22 05:15:53',
            ],
        ];

        foreach ($season_drivers as $seasonDriversData) {
            SeasonDriverEloquent::updateOrCreate(
                ['id' => $seasonDriversData['id']],
                $seasonDriversData
            );
        }

        // Re-enable foreign key checks
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $this->command->info('SeasonDriversBackupSeeder seeded successfully. Total records: ' . count($season_drivers));
    }
}
